StarlingX open source release updates
Signed-off-by: Dean Troyer <dtroyer@gmail.com>

diff --git a/ocf/ceilometer-agent-notification b/ocf/ceilometer-agent-notification
--- a/ocf/ceilometer-agent-notification
+++ b/ocf/ceilometer-agent-notification
@@ -1,9 +1,9 @@
 #!/bin/sh
 #
 #
-# OpenStack Cinder Scheduler Service (cinder-schedule)
+# OpenStack Ceilometer Central Agent Service (ceilometer-agent-notification)
 #
-# Description: Manages an OpenStack Cinder Scheduler Service (cinder-schedule) process as an HA resource
+# Description: Manages an OpenStack Ceilometer Central Agent Service (ceilometer-agent-notification) process as an HA resource
 #
 # Authors: Emilien Macchi
 # Mainly inspired by the Nova Scheduler resource agent written by Sebastien Han
@@ -11,7 +11,7 @@
 # Support: openstack@lists.launchpad.net
 # License: Apache Software License (ASL) 2.0
 #
-# Copyright (c) 2014 Wind River Systems, Inc.
+# Copyright (c) 2014-2016 Wind River Systems, Inc.
 #
 # SPDX-License-Identifier: Apache-2.0
 #
@@ -21,6 +21,7 @@
 # OCF instance parameters:
 # OCF_RESKEY_binary
 # OCF_RESKEY_config
+# OCF_RESKEY_pipeline
 # OCF_RESKEY_user
 # OCF_RESKEY_pid
 # OCF_RESKEY_monitor_binary
@@ -31,19 +32,22 @@
 
 : ${OCF_FUNCTIONS_DIR=${OCF_ROOT}/lib/heartbeat}
 . ${OCF_FUNCTIONS_DIR}/ocf-shellfuncs
+. /usr/bin/tsconfig
 
 #######################################################################
 
 # Fill in some defaults if no values are specified
 
-OCF_RESKEY_binary_default="cinder-scheduler"
-OCF_RESKEY_config_default="/etc/cinder/cinder.conf"
-OCF_RESKEY_user_default="cinder"
+OCF_RESKEY_binary_default="ceilometer-agent-notification"
+OCF_RESKEY_config_default="/etc/ceilometer/ceilometer.conf"
+OCF_RESKEY_pipeline_default="/opt/cgcs/ceilometer/${SW_VERSION}/pipeline.yaml"
+OCF_RESKEY_user_default="root"
 OCF_RESKEY_pid_default="$HA_RSCTMP/$OCF_RESOURCE_INSTANCE.pid"
 OCF_RESKEY_amqp_server_port_default="5672"
 
 : ${OCF_RESKEY_binary=${OCF_RESKEY_binary_default}}
 : ${OCF_RESKEY_config=${OCF_RESKEY_config_default}}
+: ${OCF_RESKEY_pipeline=${OCF_RESKEY_pipeline_default}}
 : ${OCF_RESKEY_user=${OCF_RESKEY_user_default}}
 : ${OCF_RESKEY_pid=${OCF_RESKEY_pid_default}}
 : ${OCF_RESKEY_amqp_server_port=${OCF_RESKEY_amqp_server_port_default}}
@@ -54,7 +58,7 @@ usage() {
     cat <<UEND
         usage: $0 (start|stop|validate-all|meta-data|status|monitor)
 
-        $0 manages an OpenStack Cinder Scheduler Service (cinder-schedule) process as an HA resource
+        $0 manages an OpenStack Ceilometer Central Agent Service (ceilometer-agent-notification) process as an HA resource
 
         The 'start' operation starts the scheduler service.
         The 'stop' operation stops the scheduler service.
@@ -70,46 +74,54 @@ meta_data() {
     cat <<END
 <?xml version="1.0"?>
 <!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
-<resource-agent name="cinder-schedule">
+<resource-agent name="ceilometer-agent-notification">
 <version>1.0</version>
 
 <longdesc lang="en">
-Resource agent for the OpenStack Cinder Scheduler Service (cinder-schedule)
-May manage a cinder-schedule instance or a clone set that
-creates a distributed cinder-schedule cluster.
+Resource agent for the OpenStack Ceilometer Central Agent Service (ceilometer-agent-notification)
+May manage a ceilometer-agent-notification instance or a clone set that
+creates a distributed ceilometer-agent-notification cluster.
 </longdesc>
-<shortdesc lang="en">Manages the OpenStack Cinder Scheduler Service (cinder-schedule)</shortdesc>
+<shortdesc lang="en">Manages the OpenStack Ceilometer Central Agent Service (ceilometer-agent-notification)</shortdesc>
 <parameters>
 
 <parameter name="binary" unique="0" required="0">
 <longdesc lang="en">
-Location of the OpenStack Cinder Scheduler server binary (cinder-schedule)
+Location of the OpenStack Ceilometer Central Agent server binary (ceilometer-agent-notification)
 </longdesc>
-<shortdesc lang="en">OpenStack Cinder Scheduler server binary (cinder-schedule)</shortdesc>
+<shortdesc lang="en">OpenStack Ceilometer Central Agent server binary (ceilometer-agent-notification)</shortdesc>
 <content type="string" default="${OCF_RESKEY_binary_default}" />
 </parameter>
 
 <parameter name="config" unique="0" required="0">
 <longdesc lang="en">
-Location of the OpenStack Cinder Scheduler Service (cinder-schedule) configuration file
+Location of the OpenStack Ceilometer Central Agent Service (ceilometer-agent-notification) configuration file
 </longdesc>
-<shortdesc lang="en">OpenStack Cinder Scheduler (cinder-schedule registry) config file</shortdesc>
+<shortdesc lang="en">OpenStack Ceilometer Central Agent (ceilometer-agent-notification registry) config file</shortdesc>
 <content type="string" default="${OCF_RESKEY_config_default}" />
+</parameter>
+
+<parameter name="pipeline" unique="0" required="0">
+<longdesc lang="en">
+Location of the OpenStack Ceilometer Central Agent Service (ceilometer-agent-notification) pipeline file
+</longdesc>
+<shortdesc lang="en">OpenStack Ceilometer Central Agent (ceilometer-agent-notification registry) pipeline file</shortdesc>
+<content type="string" default="${OCF_RESKEY_pipeline_default}" />
 </parameter>
 
 <parameter name="user" unique="0" required="0">
 <longdesc lang="en">
-User running OpenStack Cinder Scheduler Service (cinder-schedule)
+User running OpenStack Ceilometer Central Agent Service (ceilometer-agent-notification)
 </longdesc>
-<shortdesc lang="en">OpenStack Cinder Scheduler Service (cinder-schedule) user</shortdesc>
+<shortdesc lang="en">OpenStack Ceilometer Central Agent Service (ceilometer-agent-notification) user</shortdesc>
 <content type="string" default="${OCF_RESKEY_user_default}" />
 </parameter>
 
 <parameter name="pid" unique="0" required="0">
 <longdesc lang="en">
-The pid file to use for this OpenStack Cinder Scheduler Service (cinder-schedule) instance
+The pid file to use for this OpenStack Ceilometer Central Agent Service (ceilometer-agent-notification) instance
 </longdesc>
-<shortdesc lang="en">OpenStack Cinder Scheduler Service (cinder-schedule) pid file</shortdesc>
+<shortdesc lang="en">OpenStack Ceilometer Central Agent Service (ceilometer-agent-notification) pid file</shortdesc>
 <content type="string" default="${OCF_RESKEY_pid_default}" />
 </parameter>
 
@@ -124,9 +136,9 @@ The listening port number of the AMQP server. Use for monitoring purposes
 
 <parameter name="additional_parameters" unique="0" required="0">
 <longdesc lang="en">
-Additional parameters to pass on to the OpenStack Cinder Scheduler Service (cinder-schedule)
+Additional parameters to pass on to the OpenStack Ceilometer Central Agent Service (ceilometer-agent-notification)
 </longdesc>
-<shortdesc lang="en">Additional parameters for cinder-schedule</shortdesc>
+<shortdesc lang="en">Additional parameters for ceilometer-agent-notification</shortdesc>
 <content type="string" />
 </parameter>
 
@@ -147,7 +159,7 @@ END
 #######################################################################
 # Functions invoked by resource manager actions
 
-cinder_scheduler_check_port() {
+ceilometer_agent_notification_check_port() {
 # This function has been taken from the squid RA and improved a bit
 # The length of the integer must be 4
 # Examples of valid port: "1080", "0080"
@@ -155,7 +167,7 @@ cinder_scheduler_check_port() {
 
     local int
     local cnt
-    
+
     int="$1"
     cnt=${#int}
     echo $int |egrep -qx '[0-9]+(:[0-9]+)?(,[0-9]+(:[0-9]+)?)*'
@@ -166,13 +178,13 @@ cinder_scheduler_check_port() {
     fi
 }
 
-cinder_scheduler_validate() {
+ceilometer_agent_notification_validate() {
     local rc
 
     check_binary $OCF_RESKEY_binary
     check_binary netstat
-    cinder_scheduler_check_port $OCF_RESKEY_amqp_server_port
-    
+    ceilometer_agent_notification_check_port $OCF_RESKEY_amqp_server_port
+
     # A config file on shared storage that is not available
     # during probes is OK.
     if [ ! -f $OCF_RESKEY_config ]; then
@@ -193,12 +205,12 @@ cinder_scheduler_validate() {
     true
 }
 
-cinder_scheduler_status() {
+ceilometer_agent_notification_status() {
     local pid
     local rc
 
     if [ ! -f $OCF_RESKEY_pid ]; then
-        ocf_log info "OpenStack Cinder Scheduler (cinder-schedule) is not running"
+        ocf_log info "OpenStack Ceilometer Central Agent (ceilometer-agent-notification) is not running"
         return $OCF_NOT_RUNNING
     else
         pid=`cat $OCF_RESKEY_pid`
@@ -209,18 +221,18 @@ cinder_scheduler_status() {
     if [ $rc -eq 0 ]; then
         return $OCF_SUCCESS
     else
-        ocf_log info "Old PID file found, but OpenStack Cinder Scheduler (cinder-schedule) is not running"
+        ocf_log info "Old PID file found, but OpenStack Ceilometer Central Agent (ceilometer-agent-notification) is not running"
         rm -f $OCF_RESKEY_pid
         return $OCF_NOT_RUNNING
     fi
 }
 
-cinder_scheduler_monitor() {
+ceilometer_agent_notification_monitor() {
     local rc
     local pid
     local scheduler_amqp_check
 
-    cinder_scheduler_status
+    ceilometer_agent_notification_status
     rc=$?
 
     # If status returned anything but success, return that immediately
@@ -228,52 +240,43 @@ cinder_scheduler_monitor() {
         return $rc
     fi
 
-    # Check the connections according to the PID.
-    # We are sure to hit the scheduler process and not other Cinder process with the same connection behavior (for example cinder-api)
-        pid=`cat $OCF_RESKEY_pid`
-        scheduler_amqp_check=`netstat -punt | grep -s "$OCF_RESKEY_amqp_server_port" | grep -s "$pid" | grep -qs "ESTABLISHED"`
-        rc=$?
-        if [ $rc -ne 0 ]; then
-        ocf_log err "Cinder Scheduler is not connected to the AMQP server : $rc"
-        return $OCF_NOT_RUNNING
-        fi
-
-    ocf_log debug "OpenStack Cinder Scheduler (cinder-schedule) monitor succeeded"
+    ocf_log debug "OpenStack Ceilometer Central Agent (ceilometer-agent-notification) monitor succeeded"
     return $OCF_SUCCESS
 }
 
-cinder_scheduler_start() {
+ceilometer_agent_notification_start() {
     local rc
 
-    cinder_scheduler_status
+    ceilometer_agent_notification_status
     rc=$?
     if [ $rc -eq $OCF_SUCCESS ]; then
-        ocf_log info "OpenStack Cinder Scheduler (cinder-schedule) already running"
+        ocf_log info "OpenStack Ceilometer Central Agent (ceilometer-agent-notification) already running"
         return $OCF_SUCCESS
     fi
 
-    # run the actual cinder-schedule daemon. Don't use ocf_run as we're sending the tool's output
+    # run the actual ceilometer-agent-notification daemon. Don't use ocf_run as we're sending the tool's output
     # straight to /dev/null anyway and using ocf_run would break stdout-redirection here.
     su ${OCF_RESKEY_user} -s /bin/sh -c "${OCF_RESKEY_binary} --config-file=$OCF_RESKEY_config \
+       --pipeline_cfg_file=$OCF_RESKEY_pipeline \
        $OCF_RESKEY_additional_parameters"' >> /dev/null 2>&1 & echo $!' > $OCF_RESKEY_pid
 
     # Spin waiting for the server to come up.
     while true; do
-    cinder_scheduler_monitor
+    ceilometer_agent_notification_monitor
     rc=$?
     [ $rc -eq $OCF_SUCCESS ] && break
     if [ $rc -ne $OCF_NOT_RUNNING ]; then
-        ocf_log err "OpenStack Cinder Scheduler (cinder-schedule) start failed"
+        ocf_log err "OpenStack Ceilometer Central Agent (ceilometer-agent-notification) start failed"
         exit $OCF_ERR_GENERIC
     fi
     sleep 1
     done
 
-    ocf_log info "OpenStack Cinder Scheduler (cinder-schedule) started"
+    ocf_log info "OpenStack Ceilometer Central Agent (ceilometer-agent-notification) started"
     return $OCF_SUCCESS
 }
 
-cinder_scheduler_confirm_stop() {
+ceilometer_agent_notification_confirm_stop() {
     local my_bin
     local my_processes
 
@@ -287,15 +290,15 @@ cinder_scheduler_confirm_stop() {
     fi
 }
 
-cinder_scheduler_stop() {
+ceilometer_agent_notification_stop() {
     local rc
     local pid
 
-    cinder_scheduler_status
+    ceilometer_agent_notification_status
     rc=$?
     if [ $rc -eq $OCF_NOT_RUNNING ]; then
-        ocf_log info "OpenStack Cinder Scheduler (cinder-schedule) already stopped"
-        cinder_scheduler_confirm_stop
+        ocf_log info "OpenStack Ceilometer Central Agent (ceilometer-agent-notification) already stopped"
+        ceilometer_agent_notification_confirm_stop
         return $OCF_SUCCESS
     fi
 
@@ -304,39 +307,39 @@ cinder_scheduler_stop() {
     ocf_run kill -s TERM $pid
     rc=$?
     if [ $rc -ne 0 ]; then
-        ocf_log err "OpenStack Cinder Scheduler (cinder-schedule) couldn't be stopped"
-        cinder_scheduler_confirm_stop
+        ocf_log err "OpenStack Ceilometer Central Agent (ceilometer-agent-notification) couldn't be stopped"
+        ceilometer_agent_notification_confirm_stop
         exit $OCF_ERR_GENERIC
     fi
 
     # stop waiting
-    shutdown_timeout=15
+    shutdown_timeout=2
     if [ -n "$OCF_RESKEY_CRM_meta_timeout" ]; then
         shutdown_timeout=$((($OCF_RESKEY_CRM_meta_timeout/1000)-5))
     fi
     count=0
     while [ $count -lt $shutdown_timeout ]; do
-        cinder_scheduler_status
+        ceilometer_agent_notification_status
         rc=$?
         if [ $rc -eq $OCF_NOT_RUNNING ]; then
             break
         fi
         count=`expr $count + 1`
         sleep 1
-        ocf_log debug "OpenStack Cinder Scheduler (cinder-schedule) still hasn't stopped yet. Waiting ..."
+        ocf_log debug "OpenStack Ceilometer Central Agent (ceilometer-agent-notification) still hasn't stopped yet. Waiting ..."
     done
 
-    cinder_scheduler_status
+    ceilometer_agent_notification_status
     rc=$?
     if [ $rc -ne $OCF_NOT_RUNNING ]; then
         # SIGTERM didn't help either, try SIGKILL
-        ocf_log info "OpenStack Cinder Scheduler (cinder-schedule) failed to stop after ${shutdown_timeout}s \
+        ocf_log info "OpenStack Ceilometer Central Agent (ceilometer-agent-notification) failed to stop after ${shutdown_timeout}s \
           using SIGTERM. Trying SIGKILL ..."
         ocf_run kill -s KILL $pid
     fi
-    cinder_scheduler_confirm_stop
+    ceilometer_agent_notification_confirm_stop
 
-    ocf_log info "OpenStack Cinder Scheduler (cinder-schedule) stopped"
+    ocf_log info "OpenStack Ceilometer Central Agent (ceilometer-agent-notification) stopped"
 
     rm -f $OCF_RESKEY_pid
 
@@ -353,14 +356,14 @@ case "$1" in
 esac
 
 # Anything except meta-data and help must pass validation
-cinder_scheduler_validate || exit $?
+ceilometer_agent_notification_validate || exit $?
 
 # What kind of method was invoked?
 case "$1" in
-  start) cinder_scheduler_start;;
-  stop) cinder_scheduler_stop;;
-  status) cinder_scheduler_status;;
-  monitor) cinder_scheduler_monitor;;
+  start) ceilometer_agent_notification_start;;
+  stop) ceilometer_agent_notification_stop;;
+  status) ceilometer_agent_notification_status;;
+  monitor) ceilometer_agent_notification_monitor;;
   validate-all) ;;
   *) usage
                 exit $OCF_ERR_UNIMPLEMENTED;;
diff --git a/ocf/cinder-volume b/ocf/cinder-volume
--- a/ocf/cinder-volume
+++ b/ocf/cinder-volume
@@ -11,6 +11,12 @@
 # Support:      openstack@lists.launchpad.net
 # License:      Apache Software License (ASL) 2.0
 #
+# (c) 2012      hastexo Professional Services GmbH
+#
+# Copyright (c) 2014 Wind River Systems, Inc.
+#
+# SPDX-License-Identifier: Apache-2.0
+#
 #
 # See usage() function below for more details ...
 #
@@ -26,6 +32,7 @@
 
 : ${OCF_FUNCTIONS_DIR=${OCF_ROOT}/lib/heartbeat}
 . ${OCF_FUNCTIONS_DIR}/ocf-shellfuncs
+. /usr/bin/tsconfig
 
 #######################################################################
 
@@ -46,6 +53,20 @@ OCF_RESKEY_multibackend_default="false"
 : ${OCF_RESKEY_multibackend=${OCF_RESKEY_multibackend_default}}
 
 #######################################################################
+
+#######################################################################
+
+#
+# The following file is used to determine if Cinder-Volume should be
+# failed if the AMQP check does not pass.  Cinder-Volume initializes
+# it's backend before connecting to Rabbit.  In Ceph configurations,
+# Cinder-Volume will not connect to Rabbit until the storage blades
+# are provisioned (this can take a long time, no need to restart the
+# process over and over again).
+VOLUME_FAIL_ON_AMQP_CHECK_FILE="$HA_RSCTMP/$OCF_RESOURCE_INSTANCE.fail_on_amqp_check"
+
+#######################################################################
+
 
 usage() {
     cat <<UEND
@@ -194,7 +215,25 @@ cinder_volume_status() {
         return $OCF_SUCCESS
     else
         ocf_log info "Old PID file found, but OpenStack Cinder Volume (cinder-volume) is not running"
+        rm -f $OCF_RESKEY_pid
         return $OCF_NOT_RUNNING
+    fi
+}
+
+cinder_volume_get_service_status() {
+    local status_file=${VOLATILE_PATH}/cinder-volume.down-after
+    if [[ -f "${status_file}" ]]; then
+        echo "exists=True"
+        if [[ "$(date -u +'%Y-%m-%d %H:%M:%S.%N')" < "$(cat ${status_file})" ]]; then
+            echo "is_up=True"
+        else
+            echo "is_up=False"
+        fi
+        return 0
+    else
+        echo "exists=False"
+        echo "is_up=False"
+        return 1
     fi
 }
 
@@ -202,6 +241,7 @@ cinder_volume_monitor() {
     local rc
     local pid
     local volume_amqp_check
+    local check_service_status=$1; shift
 
     cinder_volume_status
     rc=$?
@@ -215,14 +255,26 @@ cinder_volume_monitor() {
     pid=`cat $OCF_RESKEY_pid`
 
     if ocf_is_true "$OCF_RESKEY_multibackend"; then
+      pids=`ps -o pid --no-headers --ppid $pid`
+      rc=$?
+      if [ $rc -ne 0 ]; then
+        ocf_log err "No child processes from Cinder Volume (yet...): $rc"
+        return $OCF_NOT_RUNNING
+      fi
+
       # Grab the child's PIDs
       for i in `ps -o pid --no-headers --ppid $pid`
       do
         volume_amqp_check=`netstat -punt | grep -s "$OCF_RESKEY_amqp_server_port" | grep -s "$i" | grep -qs "ESTABLISHED"`
         rc=$?
         if [ $rc -ne 0 ]; then
-          ocf_log err "This child process from Cinder Volume is not connected to the AMQP server: $rc"
-          return $OCF_NOT_RUNNING
+          if [ -e "$VOLUME_FAIL_ON_AMQP_CHECK_FILE" ]; then
+            ocf_log err "This child process from Cinder Volume is not connected to the AMQP server: $rc"
+            return $OCF_NOT_RUNNING
+          else
+            ocf_log info "Cinder Volume initializing, child process is not connected to the AMQP server: $rc"
+            return $OCF_SUCCESS
+          fi
         fi
       done
     else
@@ -232,9 +284,56 @@ cinder_volume_monitor() {
       volume_amqp_check=`netstat -punt | grep -s "$OCF_RESKEY_amqp_server_port" | grep -s "$pid" | grep -qs "ESTABLISHED"`
       rc=$?
       if [ $rc -ne 0 ]; then
+        if [ -e "$VOLUME_FAIL_ON_AMQP_CHECK_FILE" ]; then
           ocf_log err "Cinder Volume is not connected to the AMQP server: $rc"
           return $OCF_NOT_RUNNING
+        else
+          ocf_log info "Cinder Volume initializing, not connected to the AMQP server: $rc"
+          return $OCF_SUCCESS
+        fi
       fi
+    fi
+
+    touch $VOLUME_FAIL_ON_AMQP_CHECK_FILE  >> /dev/null 2>&1
+
+    if [ $check_service_status == "check-service-status" ]; then
+        local retries_left
+        local retry_interval
+
+        retries_left=3
+        retry_interval=3
+        while [ $retries_left -gt 0 ]; do
+            retries_left=`expr $retries_left - 1`
+            status=$(cinder_volume_get_service_status)
+            rc=$?
+            if [ $rc -ne 0 ]; then
+                ocf_log err "Unable to get Cinder Volume status"
+                if [ $retries_left -gt 0 ]; then
+                    sleep $retry_interval
+                    continue
+                else
+                    return $OCF_ERR_GENERIC
+                fi
+            fi
+
+            local exists
+            local is_up
+            eval $status
+
+            if [ "$exists" == "True" ] && [ "$is_up" == "False" ]; then
+                ocf_log err "Cinder Volume service status is down"
+                if [ $retries_left -gt 0 ]; then
+                    sleep $retry_interval
+                    continue
+                else
+                    ocf_log info "Trigger Cinder Volume guru meditation report"
+                    ocf_run kill -s USR2 $pid
+                    return $OCF_ERR_GENERIC
+                fi
+            fi
+
+            break
+        done
     fi
 
     ocf_log debug "OpenStack Cinder Volume (cinder-volume) monitor succeeded"
@@ -243,6 +342,10 @@ cinder_volume_monitor() {
 
 cinder_volume_start() {
     local rc
+
+    if [ -e "$VOLUME_FAIL_ON_AMQP_CHECK_FILE" ] ; then
+        rm $VOLUME_FAIL_ON_AMQP_CHECK_FILE >> /dev/null 2>&1 
+    fi
 
     cinder_volume_status
     rc=$?
@@ -273,14 +376,37 @@ cinder_volume_start() {
     return $OCF_SUCCESS
 }
 
+cinder_volume_confirm_stop() {
+    local my_bin
+    local my_processes
+
+    if [ -e "$VOLUME_FAIL_ON_AMQP_CHECK_FILE" ] ; then
+        rm $VOLUME_FAIL_ON_AMQP_CHECK_FILE >> /dev/null 2>&1 
+    fi
+    
+    my_binary=`which ${OCF_RESKEY_binary}`
+    my_processes=`pgrep -l -f "^(python|/usr/bin/python|/usr/bin/python2) ${my_binary}([^\w-]|$)"`
+
+    if [ -n "${my_processes}" ]
+    then
+        ocf_log info "About to SIGKILL the following: ${my_processes}"
+        pkill -KILL -f "^(python|/usr/bin/python|/usr/bin/python2) ${my_binary}([^\w-]|$)"
+    fi
+}
+
 cinder_volume_stop() {
     local rc
     local pid
 
+    if [ -e "$VOLUME_FAIL_ON_AMQP_CHECK_FILE" ] ; then
+        rm $VOLUME_FAIL_ON_AMQP_CHECK_FILE >> /dev/null 2>&1 
+    fi
+    
     cinder_volume_status
     rc=$?
     if [ $rc -eq $OCF_NOT_RUNNING ]; then
         ocf_log info "OpenStack Cinder Volume (cinder-volume) already stopped"
+        cinder_volume_confirm_stop
         return $OCF_SUCCESS
     fi
 
@@ -290,6 +416,7 @@ cinder_volume_stop() {
     rc=$?
     if [ $rc -ne 0 ]; then
         ocf_log err "OpenStack Cinder Volume (cinder-volume) couldn't be stopped"
+        cinder_volume_confirm_stop
         exit $OCF_ERR_GENERIC
     fi
 
@@ -316,8 +443,9 @@ cinder_volume_stop() {
         # SIGTERM didn't help either, try SIGKILL
         ocf_log info "OpenStack Cinder Volume (cinder-volume) failed to stop after ${shutdown_timeout}s \
           using SIGTERM. Trying SIGKILL ..."
-        ocf_run kill -s KILL $pid
+        ocf_run kill -s KILL -$pid
     fi
+    cinder_volume_confirm_stop
 
     ocf_log info "OpenStack Cinder Volume (cinder-volume) stopped"
 
@@ -343,7 +471,7 @@ case "$1" in
   start)        cinder_volume_start;;
   stop)         cinder_volume_stop;;
   status)       cinder_volume_status;;
-  monitor)      cinder_volume_monitor;;
+  monitor)      cinder_volume_monitor "check-service-status";;
   validate-all) ;;
   *)            usage
                 exit $OCF_ERR_UNIMPLEMENTED;;
diff --git a/ocf/dcorch-engine b/ocf/dcorch-engine
--- a/ocf/dcorch-engine
+++ b/ocf/dcorch-engine
@@ -1,17 +1,9 @@
 #!/bin/sh
+# OpenStack DC Orchestrator Engine Service (dcorch-engine)
 #
+# Description:  Manages an OpenStack DC Orchestrator Engine Service (dcorch-engine) process as an HA resource
 #
-# OpenStack Cinder API (cinder-api)
-#
-# Description:  Manages an OpenStack Cinder API (cinder-api) process as an HA resource
-#
-# Authors:      Emilien Macchi
-# Mainly inspired by the Nova API written by Sebastien Han
-#
-# Support:      openstack@lists.launchpad.net
-# License:      Apache Software License (ASL) 2.0
-#
-# Copyright (c) 2014 Wind River Systems, Inc.
+# Copyright (c) 2017 Wind River Systems, Inc.
 #
 # SPDX-License-Identifier: Apache-2.0
 #
@@ -23,10 +15,6 @@
 #   OCF_RESKEY_config
 #   OCF_RESKEY_user
 #   OCF_RESKEY_pid
-#   OCF_RESKEY_os_username
-#   OCF_RESKEY_os_password
-#   OCF_RESKEY_os_tenant_name
-#   OCF_RESKEY_keystone_get_token_url
 #   OCF_RESKEY_additional_parameters
 #######################################################################
 # Initialization:
@@ -38,19 +26,15 @@
 
 # Fill in some defaults if no values are specified
 
-OCF_RESKEY_binary_default="cinder-api"
-OCF_RESKEY_config_default="/etc/cinder/cinder.conf"
-OCF_RESKEY_user_default="cinder"
+OCF_RESKEY_binary_default="/usr/bin/dcorch-engine"
+OCF_RESKEY_config_default="/etc/dcorch/dcorch.conf"
+OCF_RESKEY_user_default="root"
 OCF_RESKEY_pid_default="$HA_RSCTMP/$OCF_RESOURCE_INSTANCE.pid"
-OCF_RESKEY_url_default="http://127.0.0.1:8776/v1/"
-OCF_RESKEY_keystone_get_token_url_default="http://127.0.0.1:5000/v2.0/tokens"
 
 : ${OCF_RESKEY_binary=${OCF_RESKEY_binary_default}}
 : ${OCF_RESKEY_config=${OCF_RESKEY_config_default}}
 : ${OCF_RESKEY_user=${OCF_RESKEY_user_default}}
 : ${OCF_RESKEY_pid=${OCF_RESKEY_pid_default}}
-: ${OCF_RESKEY_url=${OCF_RESKEY_url_default}}
-: ${OCF_RESKEY_keystone_get_token_url=${OCF_RESKEY_keystone_get_token_url_default}}
 
 #######################################################################
 
@@ -58,14 +42,14 @@ usage() {
     cat <<UEND
         usage: $0 (start|stop|validate-all|meta-data|status|monitor)
 
-        $0 manages an OpenStack Cinder API (cinder-api) process as an HA resource 
+        $0 manages an OpenStack DC Orchestrator Engine (dcorch-engine) process as an HA resource
 
-        The 'start' operation starts the cinder-api service.
-        The 'stop' operation stops the cinder-api service.
+        The 'start' operation starts the dcorch-engine service.
+        The 'stop' operation stops the dcorch-engine service.
         The 'validate-all' operation reports whether the parameters are valid
         The 'meta-data' operation reports this RA's meta-data information
-        The 'status' operation reports whether the cinder-api service is running
-        The 'monitor' operation reports whether the cinder-api service seems to be working
+        The 'status' operation reports whether the dcorch-engine service is running
+        The 'monitor' operation reports whether the dcorch-engine service seems to be working
 
 UEND
 }
@@ -74,95 +58,52 @@ meta_data() {
     cat <<END
 <?xml version="1.0"?>
 <!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
-<resource-agent name="cinder-api">
+<resource-agent name="dcorch-engine">
 <version>1.0</version>
 
 <longdesc lang="en">
-Resource agent for the OpenStack Cinder API Service (cinder-api)
-May manage a cinder-api instance or a clone set that 
-creates a distributed cinder-api cluster.
+Resource agent for the DC Orchestrator Engine Service (dcorch-engine)
 </longdesc>
-<shortdesc lang="en">Manages the OpenStack Cinder API (cinder-api)</shortdesc>
+<shortdesc lang="en">Manages the OpenStack DC Orchestrator Engine Service(dcorch-engine)</shortdesc>
 <parameters>
 
 <parameter name="binary" unique="0" required="0">
 <longdesc lang="en">
-Location of the OpenStack Cinder API server binary (cinder-api)
+Location of the DC Orchestrator Engine binary (dcorch-engine)
 </longdesc>
-<shortdesc lang="en">OpenStack Cinder API server binary (cinder-api)</shortdesc>
+<shortdesc lang="en">DC Orchestrator Engine binary (dcorch-engine)</shortdesc>
 <content type="string" default="${OCF_RESKEY_binary_default}" />
 </parameter>
 
 <parameter name="config" unique="0" required="0">
 <longdesc lang="en">
-Location of the OpenStack Cinder API (cinder-api) configuration file
+Location of the DC Orchestrator Engine (dcorch-engine) configuration file
 </longdesc>
-<shortdesc lang="en">OpenStack Cinder API (cinder-api registry) config file</shortdesc>
+<shortdesc lang="en">DC Orchestrator Engine (dcorch-engine registry) config file</shortdesc>
 <content type="string" default="${OCF_RESKEY_config_default}" />
 </parameter>
 
 <parameter name="user" unique="0" required="0">
 <longdesc lang="en">
-User running OpenStack Cinder API (cinder-api)
+User running DC Orchestrator Engine (dcorch-engine)
 </longdesc>
-<shortdesc lang="en">OpenStack Cinder API (cinder-api) user</shortdesc>
+<shortdesc lang="en">DC Orchestrator Engine (dcorch-engine) user</shortdesc>
 <content type="string" default="${OCF_RESKEY_user_default}" />
 </parameter>
 
 <parameter name="pid" unique="0" required="0">
 <longdesc lang="en">
-The pid file to use for this OpenStack Cinder API (cinder-api) instance
+The pid file to use for this DC Orchestrator Engine (dcorch-engine) instance
 </longdesc>
-<shortdesc lang="en">OpenStack Cinder API (cinder-api) pid file</shortdesc>
+<shortdesc lang="en">DC Orchestrator Engine (dcorch-engine) pid file</shortdesc>
 <content type="string" default="${OCF_RESKEY_pid_default}" />
-</parameter>
-
-<parameter name="url" unique="0" required="0">
-<longdesc lang="en">
-The default URL to use for monitoring this instance (cinder-api) via curl. Important note: the monitor function doesn't accept http return code different than 200, for instance redirection code will generate an error. Don't forget the '/' at the end of your url endpoint. For example http://127.0.0.1:8776/v1 won't work and http://127.0.0.1:8776/v1/ will.
-</longdesc>
-<shortdesc lang="en">OpenStack Cinder API (cinder-api) monitor url</shortdesc>
-<content type="string" default="${OCF_RESKEY_url_default}" />
-</parameter>
-
-<parameter name="keystone_get_token_url" unique="0" required="0">
-<longdesc lang="en">
-The default URL to use to acquire a Cinder API (cinder-api) token for monitoring this instance
-of OpenStack Cinder API (cinder-api)
-</longdesc>
-<shortdesc lang="en">OpenStack Cinder API (cinder-api) url</shortdesc>
-<content type="string" default="${OCF_RESKEY_keystone_get_token_url_default}" />
-</parameter>
-
-<parameter name="os_username" unique="0" required="0">
-<longdesc lang="en">
-The username to use when connecting with Cinder API (cinder-api) for monitoring purposes
-</longdesc>
-<shortdesc lang="en">Cinder API (cinder-api) monitoring login</shortdesc>
-<content type="string" />
-</parameter>
-
-<parameter name="os_password" unique="0" required="0">
-<longdesc lang="en">
-The password to use when connecting Cinder API (cinder-api) for monitoring purposes
-</longdesc>
-<shortdesc lang="en">Cinder API (cinder-api) monitoring password</shortdesc>
-<content type="string" />
-</parameter>
-
-<parameter name="os_tenant_name" unique="0" required="0">
-<longdesc lang="en">
-The tenant to use when connecting Cinder API (cinder-api) for monitoring purposes
-</longdesc>
-<shortdesc lang="en">Cinder API (cinder-api) monitoring tenant</shortdesc>
-<content type="string" />
 </parameter>
 
 <parameter name="additional_parameters" unique="0" required="0">
 <longdesc lang="en">
-Additional parameters to pass on to the OpenStack Cinder API (cinder-api)
+Additional parameters to pass on to the OpenStack DC Orchestrator Engine (dcorch-engine)
 </longdesc>
-<shortdesc lang="en">Additional parameters for cinder-api</shortdesc>
+<shortdesc lang="en">Additional parameters for dcorch-engine</shortdesc>
 <content type="string" />
 </parameter>
 
@@ -183,7 +124,7 @@ END
 #######################################################################
 # Functions invoked by resource manager actions
 
-cinder_api_validate() {
+dcorch_engine_validate() {
     local rc
 
     check_binary $OCF_RESKEY_binary
@@ -192,7 +133,7 @@ cinder_api_validate() {
     check_binary grep
     check_binary cut
     check_binary head
-    
+
     # A config file on shared storage that is not available
     # during probes is OK.
     if [ ! -f $OCF_RESKEY_config ]; then
@@ -213,12 +154,12 @@ cinder_api_validate() {
     true
 }
 
-cinder_api_status() {
+dcorch_engine_status() {
     local pid
     local rc
 
     if [ ! -f $OCF_RESKEY_pid ]; then
-        ocf_log info "OpenStack Cinder API (cinder-api) is not running"
+        ocf_log info "DC Orchestrator Engine (dcorch-engine) is not running"
         return $OCF_NOT_RUNNING
     else
         pid=`cat $OCF_RESKEY_pid`
@@ -229,16 +170,16 @@ cinder_api_status() {
     if [ $rc -eq 0 ]; then
         return $OCF_SUCCESS
     else
-        ocf_log info "Old PID file found, but OpenStack Cinder API (cinder-api) is not running"
+        ocf_log info "Old PID file found, but DC Orchestrator Engine (dcorch-engine) is not running"
         rm -f $OCF_RESKEY_pid
         return $OCF_NOT_RUNNING
     fi
 }
 
-cinder_api_monitor() {
+dcorch_engine_monitor() {
     local rc
 
-    cinder_api_status
+    dcorch_engine_status
     rc=$?
 
     # If status returned anything but success, return that immediately
@@ -246,31 +187,26 @@ cinder_api_monitor() {
         return $rc
     fi
 
-    # Check detailed information about this specific version of the API.
-    if [ -n "$OCF_RESKEY_os_username"] && [ -n "$OCF_RESKEY_os_tenant_name" ] && [ -n "$OCF_RESKEY_keystone_get_token_url" ]; then
-       ./validation $OCF_RESKEY_keystone_get_token_url $OCF_RESKEY_os_username $OCF_RESKEY_os_tenant_name
-       rc=$?
-       if [ $rc -ne 0 ]; then
-           ocf_log err "Failed to connect to the OpenStack Cinder API (cinder-api): $rc"
-           return $OCF_NOT_RUNNING
-       fi
-    fi
+    # Further verify the service availibility.
 
-    ocf_log debug "OpenStack Cinder API (cinder-api) monitor succeeded"
+    ocf_log debug "DC Orchestrator Engine (dcorch-engine) monitor succeeded"
     return $OCF_SUCCESS
 }
 
-cinder_api_start() {
+dcorch_engine_start() {
     local rc
 
-    cinder_api_status
+    dcorch_engine_status
     rc=$?
     if [ $rc -eq $OCF_SUCCESS ]; then
-        ocf_log info "OpenStack Cinder API (cinder-api) already running"
+        ocf_log info "DC Orchestrator Engine (dcorch-engine) already running"
         return $OCF_SUCCESS
     fi
 
-    # run the actual cinder-api daemon. Don't use ocf_run as we're sending the tool's output
+    # Change the working dir to /, to be sure it's accesible
+    cd /
+
+    # run the actual dcorch-engine daemon. Don't use ocf_run as we're sending the tool's output
     # straight to /dev/null anyway and using ocf_run would break stdout-redirection here.
     su ${OCF_RESKEY_user} -s /bin/sh -c "${OCF_RESKEY_binary} --config-file=$OCF_RESKEY_config \
        $OCF_RESKEY_additional_parameters"' >> /dev/null 2>&1 & echo $!' > $OCF_RESKEY_pid
@@ -278,21 +214,21 @@ cinder_api_start() {
     # Spin waiting for the server to come up.
     # Let the CRM/LRM time us out if required
     while true; do
-    cinder_api_monitor
+    dcorch_engine_monitor
     rc=$?
     [ $rc -eq $OCF_SUCCESS ] && break
     if [ $rc -ne $OCF_NOT_RUNNING ]; then
-        ocf_log err "OpenStack Cinder API (cinder-api) start failed"
+        ocf_log err "DC Orchestrator Engine (dcorch-engine) start failed"
         exit $OCF_ERR_GENERIC
     fi
     sleep 1
     done
 
-    ocf_log info "OpenStack Cinder API (cinder-api) started"
+    ocf_log info "DC Orchestrator Engine (dcorch-engine) started"
     return $OCF_SUCCESS
 }
 
-cinder_api_confirm_stop() {
+dcorch_engine_confirm_stop() {
     local my_bin
     local my_processes
 
@@ -306,15 +242,15 @@ cinder_api_confirm_stop() {
     fi
 }
 
-cinder_api_stop() {
+dcorch_engine_stop() {
     local rc
     local pid
 
-    cinder_api_status
+    dcorch_engine_status
     rc=$?
     if [ $rc -eq $OCF_NOT_RUNNING ]; then
-        ocf_log info "OpenStack Cinder API (cinder-api) already stopped"
-        cinder_api_confirm_stop
+        ocf_log info "DC Orchestrator Engine (dcorch-engine) already stopped"
+        dcorch_engine_confirm_stop
         return $OCF_SUCCESS
     fi
 
@@ -323,8 +259,8 @@ cinder_api_stop() {
     ocf_run kill -s TERM $pid
     rc=$?
     if [ $rc -ne 0 ]; then
-        ocf_log err "OpenStack Cinder API (cinder-api) couldn't be stopped"
-        cinder_api_confirm_stop
+        ocf_log err "DC Orchestrator Engine (dcorch-engine) couldn't be stopped"
+        dcorch_engine_confirm_stop
         exit $OCF_ERR_GENERIC
     fi
 
@@ -335,27 +271,27 @@ cinder_api_stop() {
     fi
     count=0
     while [ $count -lt $shutdown_timeout ]; do
-        cinder_api_status
+        dcorch_engine_status
         rc=$?
         if [ $rc -eq $OCF_NOT_RUNNING ]; then
             break
         fi
         count=`expr $count + 1`
         sleep 1
-        ocf_log debug "OpenStack Cinder API (cinder-api) still hasn't stopped yet. Waiting ..."
+        ocf_log debug "DC Orchestrator Engine (dcorch-engine) still hasn't stopped yet. Waiting ..."
     done
 
-    cinder_api_status
+    dcorch_engine_status
     rc=$?
     if [ $rc -ne $OCF_NOT_RUNNING ]; then
         # SIGTERM didn't help either, try SIGKILL
-        ocf_log info "OpenStack Cinder API (cinder-api) failed to stop after ${shutdown_timeout}s \
+        ocf_log info "DC Orchestrator Engine (dcorch-engine) failed to stop after ${shutdown_timeout}s \
           using SIGTERM. Trying SIGKILL ..."
         ocf_run kill -s KILL $pid
     fi
-    cinder_api_confirm_stop
+    dcorch_engine_confirm_stop
 
-    ocf_log info "OpenStack Cinder API (cinder-api) stopped"
+    ocf_log info "DC Orchestrator Engine (dcorch-engine) stopped"
 
     rm -f $OCF_RESKEY_pid
 
@@ -372,14 +308,14 @@ case "$1" in
 esac
 
 # Anything except meta-data and help must pass validation
-cinder_api_validate || exit $?
+dcorch_engine_validate || exit $?
 
 # What kind of method was invoked?
 case "$1" in
-  start)        cinder_api_start;;
-  stop)         cinder_api_stop;;
-  status)       cinder_api_status;;
-  monitor)      cinder_api_monitor;;
+  start)        dcorch_engine_start;;
+  stop)         dcorch_engine_stop;;
+  status)       dcorch_engine_status;;
+  monitor)      dcorch_engine_monitor;;
   validate-all) ;;
   *)            usage
                 exit $OCF_ERR_UNIMPLEMENTED;;
diff --git a/ocf/dcorch-nova-api-proxy b/ocf/dcorch-nova-api-proxy
--- a/ocf/dcorch-nova-api-proxy
+++ b/ocf/dcorch-nova-api-proxy
@@ -1,17 +1,11 @@
 #!/bin/sh
+# OpenStack DC Orchestrator Nova Api Proxy Service (dcorch-nova-api-proxy)
 #
+# Description:
+#   Manages an OpenStack DC Orchestrator Nova Api Proxy Service (dcorch-nova-api-proxy)
+#   process as an HA resource
 #
-# OpenStack Nova VNC Console (nova-novncproxy)
-#
-# Description:  Manages an OpenStack Nova VNC Console (nova-novncproxy) process as an HA resource
-#
-# Authors:      Sébastien Han
-# Mainly inspired by the Glance API resource agent written by Martin Gerhard Loschwitz from Hastexo: http://goo.gl/whLpr
-#
-# Support:      openstack@lists.launchpad.net
-# License:      Apache Software License (ASL) 2.0
-#
-# Copyright (c) 2014 Wind River Systems, Inc.
+# Copyright (c) 2017 Wind River Systems, Inc.
 #
 # SPDX-License-Identifier: Apache-2.0
 #
@@ -23,8 +17,6 @@
 #   OCF_RESKEY_config
 #   OCF_RESKEY_user
 #   OCF_RESKEY_pid
-#   OCF_RESKEY_console_port
-#   OCF_RESKEY_web
 #   OCF_RESKEY_additional_parameters
 #######################################################################
 # Initialization:
@@ -36,19 +28,15 @@
 
 # Fill in some defaults if no values are specified
 
-OCF_RESKEY_binary_default="nova-novncproxy"
-OCF_RESKEY_config_default="/etc/nova/nova.conf"
-OCF_RESKEY_user_default="nova"
+OCF_RESKEY_binary_default="/usr/bin/dcorch-api-proxy"
+OCF_RESKEY_config_default="/etc/dcorch/dcorch.conf"
+OCF_RESKEY_user_default="root"
 OCF_RESKEY_pid_default="$HA_RSCTMP/$OCF_RESOURCE_INSTANCE.pid"
-OCF_RESKEY_console_port_default="6080"
-OCF_RESKEY_web_default="/usr/share/novnc/"
 
 : ${OCF_RESKEY_binary=${OCF_RESKEY_binary_default}}
 : ${OCF_RESKEY_config=${OCF_RESKEY_config_default}}
 : ${OCF_RESKEY_user=${OCF_RESKEY_user_default}}
 : ${OCF_RESKEY_pid=${OCF_RESKEY_pid_default}}
-: ${OCF_RESKEY_console_port=${OCF_RESKEY_console_port_default}}
-: ${OCF_RESKEY_web=${OCF_RESKEY_web_default}}
 
 #######################################################################
 
@@ -56,14 +44,14 @@ usage() {
     cat <<UEND
         usage: $0 (start|stop|validate-all|meta-data|status|monitor)
 
-        $0 manages an OpenStack Nova VNC Console (nova-novncproxy) process as an HA resource 
+        $0 manages an OpenStack DC Orchestrator Nova Api Proxy service (dcorch-nova-api-proxy) process as an HA resource
 
-        The 'start' operation starts the console service.
-        The 'stop' operation stops the console service.
+        The 'start' operation starts the dcorch-nova-api-proxy service.
+        The 'stop' operation stops the dcorch-nova-api-proxy service.
         The 'validate-all' operation reports whether the parameters are valid
         The 'meta-data' operation reports this RA's meta-data information
-        The 'status' operation reports whether the console service is running
-        The 'monitor' operation reports whether the console service seems to be working
+        The 'status' operation reports whether the dcorch-nova-api-proxy service is running
+        The 'monitor' operation reports whether the dcorch-nova-api-proxy service seems to be working
 
 UEND
 }
@@ -72,80 +60,62 @@ meta_data() {
     cat <<END
 <?xml version="1.0"?>
 <!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
-<resource-agent name="nova-novncproxy">
+<resource-agent name="dcorch-nova-api-proxy">
 <version>1.0</version>
 
 <longdesc lang="en">
-Resource agent for the OpenStack Nova VNC Console Service (nova-novncproxy)
-May manage a nova-novncproxy instance or a clone set that 
-creates a distributed nova-novncproxy cluster.
+Resource agent for the DC Orchestrator Nova API proxy service (dcorch-nova-api-proxy)
 </longdesc>
-<shortdesc lang="en">Manages the OpenStack Nova VNC Console (nova-novncproxy)</shortdesc>
+<shortdesc lang="en">Manages the OpenStack DC Orchestrator Nova Api Proxy Service (dcorch-nova-api-proxy)</shortdesc>
 <parameters>
 
 <parameter name="binary" unique="0" required="0">
 <longdesc lang="en">
-Location of the OpenStack Nova VNC Console server binary (nova-novncproxy)
+Location of the DC Orchestrator Nova Api proxy server binary (dcorch-nova-api-proxy)
 </longdesc>
-<shortdesc lang="en">OpenStack Nova VNC Console server binary (nova-novncproxy)</shortdesc>
+<shortdesc lang="en">DC Orchestrator Nova Api proxy server binary (dcorch-nova-api-proxy)</shortdesc>
 <content type="string" default="${OCF_RESKEY_binary_default}" />
 </parameter>
 
 <parameter name="config" unique="0" required="0">
 <longdesc lang="en">
-Location of the OpenStack Nova VNC Console (nova-novncproxy) configuration file
+Location of the DC Orchestrator Nova Api proxy (dcorch-nova-api-proxy) configuration file
 </longdesc>
-<shortdesc lang="en">OpenStack Nova VNC Console (nova-novncproxy registry) config file</shortdesc>
+<shortdesc lang="en">DC Orchestrator Nova Api proxy (dcorch-nova-api-proxy registry) config file</shortdesc>
 <content type="string" default="${OCF_RESKEY_config_default}" />
 </parameter>
 
 <parameter name="user" unique="0" required="0">
 <longdesc lang="en">
-User running OpenStack Nova VNC Console (nova-novncproxy)
+User running DC Orchestrator Nova Api proxy (dcorch-nova-api-proxy)
 </longdesc>
-<shortdesc lang="en">OpenStack Nova VNC Console (nova-novncproxy) user</shortdesc>
+<shortdesc lang="en">DC Orchestrator Nova Api proxy (dcorch-nova-api-proxy) user</shortdesc>
 <content type="string" default="${OCF_RESKEY_user_default}" />
-</parameter>
-
-<parameter name="console_port" unique="0" required="0">
-<longdesc lang="en">
-VNC console type running: nova-novnc
-</longdesc>
-<shortdesc lang="en">OpenStack Nova VNC Console (nova-novncproxy) console type</shortdesc>
-<content type="integer" default="${OCF_RESKEY_console_port_default}" />
-</parameter>
-
-<parameter name="web" unique="0" required="0">
-<longdesc lang="en">
-VNC console web URL
-</longdesc>
-<shortdesc lang="en">OpenStack Nova VNC Console (nova-novncproxy) web URL</shortdesc>
-<content type="string" default="${OCF_RESKEY_web_default}" />
 </parameter>
 
 <parameter name="pid" unique="0" required="0">
 <longdesc lang="en">
-The pid file to use for this OpenStack Nova VNC Console (nova-novncproxy) instance
+The pid file to use for this DC Orchestrator Nova Api proxy (dcorch-nova-api-proxy) instance
 </longdesc>
-<shortdesc lang="en">OpenStack Nova VNC Console (nova-novncproxy) pid file</shortdesc>
+<shortdesc lang="en">DC Orchestrator Nova Api proxy (dcorch-nova-api-proxy) pid file</shortdesc>
 <content type="string" default="${OCF_RESKEY_pid_default}" />
 </parameter>
 
 <parameter name="additional_parameters" unique="0" required="0">
 <longdesc lang="en">
-Additional parameters to pass on to the OpenStack Nova VNC Console (nova-novncproxy)
+Additional parameters to pass on to the OpenStack NovaAPI (dcorch-nova-api-proxy)
 </longdesc>
-<shortdesc lang="en">Additional parameters for nova-novncproxy</shortdesc>
+<shortdesc lang="en">Additional parameters for dcorch-nova-api-proxy</shortdesc>
 <content type="string" />
 </parameter>
 
 </parameters>
 
 <actions>
-<action name="start" timeout="10" />
-<action name="stop" timeout="15" />
-<action name="status" timeout="10" />
-<action name="monitor" timeout="5" interval="10" />
+<action name="start" timeout="20" />
+<action name="stop" timeout="20" />
+<action name="status" timeout="20" />
+<action name="monitor" timeout="10" interval="5" />
 <action name="validate-all" timeout="5" />
 <action name="meta-data" timeout="5" />
 </actions>
@@ -156,11 +126,15 @@ END
 #######################################################################
 # Functions invoked by resource manager actions
 
-nova_vnc_console_validate() {
+dcorch_nova_api_proxy_validate() {
     local rc
 
     check_binary $OCF_RESKEY_binary
-    check_binary netstat
+    check_binary curl
+    check_binary tr
+    check_binary grep
+    check_binary cut
+    check_binary head
 
     # A config file on shared storage that is not available
     # during probes is OK.
@@ -182,12 +156,12 @@ nova_vnc_console_validate() {
     true
 }
 
-nova_vnc_console_status() {
+dcorch_nova_api_proxy_status() {
     local pid
     local rc
 
     if [ ! -f $OCF_RESKEY_pid ]; then
-        ocf_log info "OpenStack Nova VNC Console (nova-novncproxy) is not running"
+        ocf_log info "DC Orchestrator Nova Api proxy (dcorch-nova-api-proxy) is not running"
         return $OCF_NOT_RUNNING
     else
         pid=`cat $OCF_RESKEY_pid`
@@ -198,17 +172,16 @@ nova_vnc_console_status() {
     if [ $rc -eq 0 ]; then
         return $OCF_SUCCESS
     else
-        ocf_log info "Old PID file found, but OpenStack Nova VNC Console (nova-novncproxy) is not running"
+        ocf_log info "Old PID file found, but DC Orchestrator Nova Api proxy (dcorch-nova-api-proxy) is not running"
         rm -f $OCF_RESKEY_pid
         return $OCF_NOT_RUNNING
     fi
 }
 
-nova_vnc_console_monitor() {
+dcorch_nova_api_proxy_monitor() {
     local rc
-    local vnc_list_check
 
-    nova_vnc_console_status
+    dcorch_nova_api_proxy_status
     rc=$?
 
     # If status returned anything but success, return that immediately
@@ -216,78 +189,72 @@ nova_vnc_console_monitor() {
         return $rc
     fi
 
-    # Check whether we are supposed to monitor by logging into nova-novncproxy
-    # and do it if that's the case.
-    # Adding -n to netstat so that dns delays will not impact this.
-	vnc_list_check=`netstat -an | grep -s "$OCF_RESKEY_console_port" | grep -qs "LISTEN"`
-    rc=$?
-    if [ $rc -ne 0 ]; then
-        ocf_log err "Nova VNC Console doesn't seem to listen on his default port: $rc"
-        return $OCF_NOT_RUNNING
-    fi
+    # Further verify the service availibility.
 
-    ocf_log debug "OpenStack Nova VNC Console (nova-novncproxy) monitor succeeded"
+    ocf_log debug "DC Orchestrator Nova Api proxy (dcorch-nova-api-proxy) monitor succeeded"
     return $OCF_SUCCESS
 }
 
-nova_vnc_console_start() {
+dcorch_nova_api_proxy_start() {
     local rc
 
-    nova_vnc_console_status
+    dcorch_nova_api_proxy_status
     rc=$?
     if [ $rc -eq $OCF_SUCCESS ]; then
-        ocf_log info "OpenStack Nova VNC Console (nova-novncproxy) already running"
+        ocf_log info "DC Orchestrator Nova Api proxy (dcorch-nova-api-proxy) already running"
         return $OCF_SUCCESS
     fi
 
     # Change the working dir to /, to be sure it's accesible
     cd /
 
-    # run the actual nova-novncproxy daemon. Don't use ocf_run as we're sending the tool's output
+    # run the actual dcorch-nova-api-proxy daemon. Don't use ocf_run as we're sending the tool's output
     # straight to /dev/null anyway and using ocf_run would break stdout-redirection here.
-    su ${OCF_RESKEY_user} -s /bin/sh -c "${OCF_RESKEY_binary} --config-file=$OCF_RESKEY_config --web /usr/share/novnc/ \
+    su ${OCF_RESKEY_user} -s /bin/sh -c "${OCF_RESKEY_binary} --config-file=$OCF_RESKEY_config --type compute \
        $OCF_RESKEY_additional_parameters"' >> /dev/null 2>&1 & echo $!' > $OCF_RESKEY_pid
 
     # Spin waiting for the server to come up.
     # Let the CRM/LRM time us out if required
     while true; do
-    nova_vnc_console_monitor
+    dcorch_nova_api_proxy_monitor
     rc=$?
     [ $rc -eq $OCF_SUCCESS ] && break
     if [ $rc -ne $OCF_NOT_RUNNING ]; then
-        ocf_log err "OpenStack Nova VNC Console (nova-novncproxy) start failed"
+        ocf_log err "DC Orchestrator Nova Api proxy (dcorch-nova-api-proxy) start failed"
         exit $OCF_ERR_GENERIC
     fi
     sleep 1
     done
 
-    ocf_log info "OpenStack Nova VNC Console (nova-novncproxy) started"
+    ocf_log info "DC Orchestrator Nova Api proxy (dcorch-nova-api-proxy) started"
     return $OCF_SUCCESS
 }
 
-nova_vnc_console_confirm_stop() {
+dcorch_nova_api_proxy_confirm_stop() {
     local my_bin
     local my_processes
 
     my_binary=`which ${OCF_RESKEY_binary}`
-    my_processes=`pgrep -l -f "^(python|/usr/bin/python|/usr/bin/python2) ${my_binary}([^\w-]|$)"`
+    my_type="compute"
+    my_processes=`pgrep -f "^(python|/usr/bin/python|/usr/bin/python2) ${my_binary} .*--type ${my_type}([^\w-]|$)"` 
 
     if [ -n "${my_processes}" ]
     then
         ocf_log info "About to SIGKILL the following: ${my_processes}"
-        pkill -KILL -f "^(python|/usr/bin/python|/usr/bin/python2) ${my_binary}([^\w-]|$)"
+        # replace the new line with with a space in the process list
+        kill -9 `echo "${my_processes}" | tr '\n' ' '`
     fi
 }
 
-nova_vnc_console_stop() {
+dcorch_nova_api_proxy_stop() {
     local rc
     local pid
 
-    nova_vnc_console_status
+    dcorch_nova_api_proxy_status
     rc=$?
     if [ $rc -eq $OCF_NOT_RUNNING ]; then
-        ocf_log info "OpenStack Nova VNC Console (nova-novncproxy) already stopped"
-        nova_vnc_console_confirm_stop
+        ocf_log info "DC Orchestrator Nova Api proxy (dcorch-nova-api-proxy) already stopped"
+        dcorch_nova_api_proxy_confirm_stop
         return $OCF_SUCCESS
     fi
 
@@ -296,8 +263,8 @@ nova_vnc_console_stop() {
     ocf_run kill -s TERM $pid
     rc=$?
     if [ $rc -ne 0 ]; then
-        ocf_log err "OpenStack Nova VNC Console (nova-novncproxy) couldn't be stopped"
-        nova_vnc_console_confirm_stop
+        ocf_log err "DC Orchestrator Nova Api proxy (dcorch-nova-api-proxy) couldn't be stopped"
+        dcorch_nova_api_proxy_confirm_stop
         exit $OCF_ERR_GENERIC
     fi
 
@@ -308,27 +275,27 @@ nova_vnc_console_stop() {
     fi
     count=0
     while [ $count -lt $shutdown_timeout ]; do
-        nova_vnc_console_status
+        dcorch_nova_api_proxy_status
         rc=$?
         if [ $rc -eq $OCF_NOT_RUNNING ]; then
             break
         fi
         count=`expr $count + 1`
         sleep 1
-        ocf_log debug "OpenStack Nova VNC Console (nova-novncproxy) still hasn't stopped yet. Waiting ..."
+        ocf_log debug "DC Orchestrator Nova Api proxy (dcorch-nova-api-proxy) still hasn't stopped yet. Waiting ..."
     done
 
-    nova_vnc_console_status
+    dcorch_nova_api_proxy_status
     rc=$?
     if [ $rc -ne $OCF_NOT_RUNNING ]; then
         # SIGTERM didn't help either, try SIGKILL
-        ocf_log info "OpenStack Nova VNC Console (nova-novncproxy) failed to stop after ${shutdown_timeout}s \
+        ocf_log info "DC Orchestrator Nova Api proxy (dcorch-nova-api-proxy) failed to stop after ${shutdown_timeout}s \
           using SIGTERM. Trying SIGKILL ..."
         ocf_run kill -s KILL $pid
     fi
-    nova_vnc_console_confirm_stop
+    dcorch_nova_api_proxy_confirm_stop
 
-    ocf_log info "OpenStack Nova VNC Console (nova-novncproxy) stopped"
+    ocf_log info "DC Orchestrator Nova Api proxy (dcorch-nova-api-proxy) stopped"
 
     rm -f $OCF_RESKEY_pid
 
@@ -345,14 +312,14 @@ case "$1" in
 esac
 
 # Anything except meta-data and help must pass validation
-nova_vnc_console_validate || exit $?
+dcorch_nova_api_proxy_validate || exit $?
 
 # What kind of method was invoked?
 case "$1" in
-  start)        nova_vnc_console_start;;
-  stop)         nova_vnc_console_stop;;
-  status)       nova_vnc_console_status;;
-  monitor)      nova_vnc_console_monitor;;
+  start)        dcorch_nova_api_proxy_start;;
+  stop)         dcorch_nova_api_proxy_stop;;
+  status)       dcorch_nova_api_proxy_status;;
+  monitor)      dcorch_nova_api_proxy_monitor;;
   validate-all) ;;
   *)            usage
                 exit $OCF_ERR_UNIMPLEMENTED;;
diff --git a/ocf/glance-registry b/ocf/glance-registry
--- a/ocf/glance-registry
+++ b/ocf/glance-registry
@@ -12,6 +12,11 @@
 #
 # (c) 2012      hastexo Professional Services GmbH
 #
+# Copyright (c) 2014 Wind River Systems, Inc.
+#
+# SPDX-License-Identifier: Apache-2.0
+#
+#
 # See usage() function below for more details ...
 #
 # OCF instance parameters:
@@ -227,14 +232,13 @@ glance_registry_status() {
         return $OCF_SUCCESS
     else
         ocf_log info "Old PID file found, but OpenStack ImageService (glance-registry) is not running"
+        rm -f $OCF_RESKEY_pid
         return $OCF_NOT_RUNNING
     fi
 }
 
 glance_registry_monitor() {
     local rc
-    local token
-    local http_code
 
     glance_registry_status
     rc=$?
@@ -246,18 +250,13 @@ glance_registry_monitor() {
 
     # Check whether we are supposed to monitor by logging into glance-registry
     # and do it if that's the case.
-    if [ -n "$OCF_RESKEY_os_username" ] && [ -n "$OCF_RESKEY_os_password" ] \
-    && [ -n "$OCF_RESKEY_os_tenant_name" ] && [ -n "$OCF_RESKEY_keystone_get_token_url" ]; then
-        token=`curl -s -d  "{\"auth\":{\"passwordCredentials\": {\"username\": \"$OCF_RESKEY_os_username\", \
-          \"password\": \"$OCF_RESKEY_os_password\"}, \"tenantName\": \"$OCF_RESKEY_os_tenant_name\"}}" \
-          -H "Content-type: application/json" $OCF_RESKEY_keystone_get_token_url | tr ',' '\n' | grep '"id":' \
-          | cut -d'"' -f4 | head --lines 1` 
-        http_code=`curl --write-out %{http_code} --output /dev/null -sH "X-Auth-Token: $token" $OCF_RESKEY_url`
-        rc=$?
-        if [ $rc -ne 0 ] || [ $http_code -ne 200 ]; then
-            ocf_log err "Failed to connect to the OpenStack ImageService (glance-registry): $rc and $http_code"
-            return $OCF_NOT_RUNNING
-        fi
+    if [ -n "$OCF_RESKEY_os_username"] && [ -n "$OCF_RESKEY_os_tenant_name" ] && [ -n "$OCF_RESKEY_keystone_get_token_url" ]; then
+       ./validation $OCF_RESKEY_keystone_get_token_url $OCF_RESKEY_os_username $OCF_RESKEY_os_tenant_name
+       rc=$?
+       if [ $rc -ne 0 ]; then
+           ocf_log err "Failed to connect to the OpenStack ImageService (glance-registry): $rc"
+           return $OCF_NOT_RUNNING
+       fi
     fi
 
     ocf_log debug "OpenStack ImageService (glance-registry) monitor succeeded"
@@ -296,6 +295,20 @@ glance_registry_start() {
     return $OCF_SUCCESS
 }
 
+glance_registry_confirm_stop() {
+    local my_bin
+    local my_processes
+
+    my_binary=`which ${OCF_RESKEY_binary}`
+    my_processes=`pgrep -l -f "^(python|/usr/bin/python|/usr/bin/python2) ${my_binary}([^\w-]|$)"`
+
+    if [ -n "${my_processes}" ]
+    then
+        ocf_log info "About to SIGKILL the following: ${my_processes}"
+        pkill -KILL -f "^(python|/usr/bin/python|/usr/bin/python2) ${my_binary}([^\w-]|$)"
+    fi
+}
+
 glance_registry_stop() {
     local rc
     local pid
@@ -304,6 +317,7 @@ glance_registry_stop() {
     rc=$?
     if [ $rc -eq $OCF_NOT_RUNNING ]; then
         ocf_log info "OpenStack ImageService (glance-registry) already stopped"
+        glance_registry_confirm_stop
         return $OCF_SUCCESS
     fi
 
@@ -313,6 +327,7 @@ glance_registry_stop() {
     rc=$?
     if [ $rc -ne 0 ]; then
         ocf_log err "OpenStack ImageService (glance-registry) couldn't be stopped"
+        glance_registry_confirm_stop
         exit $OCF_ERR_GENERIC
     fi
 
@@ -341,6 +356,7 @@ glance_registry_stop() {
           using SIGTERM. Trying SIGKILL ..."
         ocf_run kill -s KILL $pid
     fi
+    glance_registry_confirm_stop
 
     ocf_log info "OpenStack ImageService (glance-registry) stopped"
 
diff --git a/ocf/heat-api b/ocf/heat-api
--- a/ocf/heat-api
+++ b/ocf/heat-api
@@ -1,12 +1,11 @@
 #!/bin/sh
 #
 #
-# OpenStack Cinder API (cinder-api)
+# OpenStack Orchestration Engine Service (heat-api)
 #
-# Description:  Manages an OpenStack Cinder API (cinder-api) process as an HA resource
+# Description:  Manages an OpenStack Orchestration Engine Service (heat-api) process as an HA resource
 #
 # Authors:      Emilien Macchi
-# Mainly inspired by the Nova API written by Sebastien Han
 #
 # Support:      openstack@lists.launchpad.net
 # License:      Apache Software License (ASL) 2.0
@@ -23,10 +22,8 @@
 #   OCF_RESKEY_config
 #   OCF_RESKEY_user
 #   OCF_RESKEY_pid
-#   OCF_RESKEY_os_username
-#   OCF_RESKEY_os_password
-#   OCF_RESKEY_os_tenant_name
-#   OCF_RESKEY_keystone_get_token_url
+#   OCF_RESKEY_monitor_binary
+#   OCF_RESKEY_server_port
 #   OCF_RESKEY_additional_parameters
 #######################################################################
 # Initialization:
@@ -38,19 +35,17 @@
 
 # Fill in some defaults if no values are specified
 
-OCF_RESKEY_binary_default="cinder-api"
-OCF_RESKEY_config_default="/etc/cinder/cinder.conf"
-OCF_RESKEY_user_default="cinder"
+OCF_RESKEY_binary_default="heat-api"
+OCF_RESKEY_config_default="/etc/heat/heat.conf"
+OCF_RESKEY_user_default="heat"
 OCF_RESKEY_pid_default="$HA_RSCTMP/$OCF_RESOURCE_INSTANCE.pid"
-OCF_RESKEY_url_default="http://127.0.0.1:8776/v1/"
-OCF_RESKEY_keystone_get_token_url_default="http://127.0.0.1:5000/v2.0/tokens"
+OCF_RESKEY_server_port_default="8004"
 
 : ${OCF_RESKEY_binary=${OCF_RESKEY_binary_default}}
 : ${OCF_RESKEY_config=${OCF_RESKEY_config_default}}
 : ${OCF_RESKEY_user=${OCF_RESKEY_user_default}}
 : ${OCF_RESKEY_pid=${OCF_RESKEY_pid_default}}
-: ${OCF_RESKEY_url=${OCF_RESKEY_url_default}}
-: ${OCF_RESKEY_keystone_get_token_url=${OCF_RESKEY_keystone_get_token_url_default}}
+: ${OCF_RESKEY_server_port=${OCF_RESKEY_server_port_default}}
 
 #######################################################################
 
@@ -58,14 +53,14 @@ usage() {
     cat <<UEND
         usage: $0 (start|stop|validate-all|meta-data|status|monitor)
 
-        $0 manages an OpenStack Cinder API (cinder-api) process as an HA resource 
+        $0 manages an OpenStack Orchestration Engine Service (heat-api) process as an HA resource
 
-        The 'start' operation starts the cinder-api service.
-        The 'stop' operation stops the cinder-api service.
+        The 'start' operation starts the heat-api service.
+        The 'stop' operation stops the heat-api service.
         The 'validate-all' operation reports whether the parameters are valid
         The 'meta-data' operation reports this RA's meta-data information
-        The 'status' operation reports whether the cinder-api service is running
-        The 'monitor' operation reports whether the cinder-api service seems to be working
+        The 'status' operation reports whether the heat-api service is running
+        The 'monitor' operation reports whether the heat-api service seems to be working
 
 UEND
 }
@@ -74,95 +69,63 @@ meta_data() {
     cat <<END
 <?xml version="1.0"?>
 <!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
-<resource-agent name="cinder-api">
+<resource-agent name="heat-api">
 <version>1.0</version>
 
 <longdesc lang="en">
-Resource agent for the OpenStack Cinder API Service (cinder-api)
-May manage a cinder-api instance or a clone set that 
-creates a distributed cinder-api cluster.
+Resource agent for the OpenStack Orchestration Engine Service (heat-api)
+May manage a heat-api instance or a clone set that
+creates a distributed heat-api cluster.
 </longdesc>
-<shortdesc lang="en">Manages the OpenStack Cinder API (cinder-api)</shortdesc>
+<shortdesc lang="en">Manages the OpenStack Orchestration Engine Service (heat-api)</shortdesc>
 <parameters>
 
 <parameter name="binary" unique="0" required="0">
 <longdesc lang="en">
-Location of the OpenStack Cinder API server binary (cinder-api)
+Location of the OpenStack Orchestration Engine server binary (heat-api)
 </longdesc>
-<shortdesc lang="en">OpenStack Cinder API server binary (cinder-api)</shortdesc>
+<shortdesc lang="en">OpenStack Orchestration Engine server binary (heat-api)</shortdesc>
 <content type="string" default="${OCF_RESKEY_binary_default}" />
 </parameter>
 
 <parameter name="config" unique="0" required="0">
 <longdesc lang="en">
-Location of the OpenStack Cinder API (cinder-api) configuration file
+Location of the OpenStack Orchestration Engine Service (heat-api) configuration file
 </longdesc>
-<shortdesc lang="en">OpenStack Cinder API (cinder-api registry) config file</shortdesc>
+<shortdesc lang="en">OpenStack Orchestration Engine (heat-api) config file</shortdesc>
 <content type="string" default="${OCF_RESKEY_config_default}" />
 </parameter>
 
 <parameter name="user" unique="0" required="0">
 <longdesc lang="en">
-User running OpenStack Cinder API (cinder-api)
+User running OpenStack Orchestration Engine Service (heat-api)
 </longdesc>
-<shortdesc lang="en">OpenStack Cinder API (cinder-api) user</shortdesc>
+<shortdesc lang="en">OpenStack Orchestration Engine Service (heat-api) user</shortdesc>
 <content type="string" default="${OCF_RESKEY_user_default}" />
 </parameter>
 
 <parameter name="pid" unique="0" required="0">
 <longdesc lang="en">
-The pid file to use for this OpenStack Cinder API (cinder-api) instance
+The pid file to use for this OpenStack Orchestration Engine Service (heat-api) instance
 </longdesc>
-<shortdesc lang="en">OpenStack Cinder API (cinder-api) pid file</shortdesc>
+<shortdesc lang="en">OpenStack Orchestration Engine Service (heat-api) pid file</shortdesc>
 <content type="string" default="${OCF_RESKEY_pid_default}" />
 </parameter>
 
-<parameter name="url" unique="0" required="0">
-<longdesc lang="en">
-The default URL to use for monitoring this instance (cinder-api) via curl. Important note: the monitor function doesn't accept http return code different than 200, for instance redirection code will generate an error. Don't forget the '/' at the end of your url endpoint. For example http://127.0.0.1:8776/v1 won't work and http://127.0.0.1:8776/v1/ will.
-</longdesc>
-<shortdesc lang="en">OpenStack Cinder API (cinder-api) monitor url</shortdesc>
-<content type="string" default="${OCF_RESKEY_url_default}" />
-</parameter>
+<parameter name="server_port" unique="0" required="0">                                                                                                                        
+<longdesc lang="en">                                                                                                                                                          
+The listening port number of the heat-api server.
 
-<parameter name="keystone_get_token_url" unique="0" required="0">
-<longdesc lang="en">
-The default URL to use to acquire a Cinder API (cinder-api) token for monitoring this instance
-of OpenStack Cinder API (cinder-api)
-</longdesc>
-<shortdesc lang="en">OpenStack Cinder API (cinder-api) url</shortdesc>
-<content type="string" default="${OCF_RESKEY_keystone_get_token_url_default}" />
-</parameter>
-
-<parameter name="os_username" unique="0" required="0">
-<longdesc lang="en">
-The username to use when connecting with Cinder API (cinder-api) for monitoring purposes
-</longdesc>
-<shortdesc lang="en">Cinder API (cinder-api) monitoring login</shortdesc>
-<content type="string" />
-</parameter>
-
-<parameter name="os_password" unique="0" required="0">
-<longdesc lang="en">
-The password to use when connecting Cinder API (cinder-api) for monitoring purposes
-</longdesc>
-<shortdesc lang="en">Cinder API (cinder-api) monitoring password</shortdesc>
-<content type="string" />
-</parameter>
-
-<parameter name="os_tenant_name" unique="0" required="0">
-<longdesc lang="en">
-The tenant to use when connecting Cinder API (cinder-api) for monitoring purposes
-</longdesc>
-<shortdesc lang="en">Cinder API (cinder-api) monitoring tenant</shortdesc>
-<content type="string" />
+</longdesc>                                                                                                                                                                   
+<shortdesc lang="en">heat-api listening port</shortdesc>                                                                                                                      
+<content type="integer" default="${OCF_RESKEY_server_port_default}" />                                                                                                        
 </parameter>
 
 <parameter name="additional_parameters" unique="0" required="0">
 <longdesc lang="en">
-Additional parameters to pass on to the OpenStack Cinder API (cinder-api)
+Additional parameters to pass on to the OpenStack Orchestration Engine Service (heat-api)
 </longdesc>
-<shortdesc lang="en">Additional parameters for cinder-api</shortdesc>
+<shortdesc lang="en">Additional parameters for heat-api</shortdesc>
 <content type="string" />
 </parameter>
 
@@ -172,7 +135,7 @@ Additional parameters to pass on to the OpenStack Cinder API (cinder-api)
 <action name="start" timeout="20" />
 <action name="stop" timeout="20" />
 <action name="status" timeout="20" />
-<action name="monitor" timeout="10" interval="5" />
+<action name="monitor" timeout="30" interval="20" />
 <action name="validate-all" timeout="5" />
 <action name="meta-data" timeout="5" />
 </actions>
@@ -183,16 +146,32 @@ END
 #######################################################################
 # Functions invoked by resource manager actions
 
-cinder_api_validate() {
+heat_api_check_port() {
+# This function has been taken from the squid RA and improved a bit
+# The length of the integer must be 4
+# Examples of valid port: "1080", "0080"
+# Examples of invalid port: "1080bad", "0", "0000", ""
+
+    local int
+    local cnt
+
+    int="$1"
+    cnt=${#int}
+    echo $int |egrep -qx '[0-9]+(:[0-9]+)?(,[0-9]+(:[0-9]+)?)*'
+
+    if [ $? -ne 0 ] || [ $cnt -ne 4 ]; then
+        ocf_log err "Invalid port number: $1"
+        exit $OCF_ERR_CONFIGURED
+    fi
+}
+
+heat_api_validate() {
     local rc
 
     check_binary $OCF_RESKEY_binary
-    check_binary curl
-    check_binary tr
-    check_binary grep
-    check_binary cut
-    check_binary head
-    
+    check_binary netstat
+    heat_api_check_port $OCF_RESKEY_server_port
+
     # A config file on shared storage that is not available
     # during probes is OK.
     if [ ! -f $OCF_RESKEY_config ]; then
@@ -213,12 +192,12 @@ cinder_api_validate() {
     true
 }
 
-cinder_api_status() {
+heat_api_status() {
     local pid
     local rc
 
     if [ ! -f $OCF_RESKEY_pid ]; then
-        ocf_log info "OpenStack Cinder API (cinder-api) is not running"
+        ocf_log info "OpenStack Orchestration Engine (heat-api) is not running"
         return $OCF_NOT_RUNNING
     else
         pid=`cat $OCF_RESKEY_pid`
@@ -229,16 +208,19 @@ cinder_api_status() {
     if [ $rc -eq 0 ]; then
         return $OCF_SUCCESS
     else
-        ocf_log info "Old PID file found, but OpenStack Cinder API (cinder-api) is not running"
+        ocf_log info "Old PID file found, but OpenStack Orchestration Engine (heat-api) is not running"
         rm -f $OCF_RESKEY_pid
         return $OCF_NOT_RUNNING
     fi
 }
 
-cinder_api_monitor() {
+heat_api_monitor() {
     local rc
+    local pid
+    local rc_db
+    local engine_db_check
 
-    cinder_api_status
+    heat_api_status
     rc=$?
 
     # If status returned anything but success, return that immediately
@@ -246,53 +228,50 @@ cinder_api_monitor() {
         return $rc
     fi
 
-    # Check detailed information about this specific version of the API.
-    if [ -n "$OCF_RESKEY_os_username"] && [ -n "$OCF_RESKEY_os_tenant_name" ] && [ -n "$OCF_RESKEY_keystone_get_token_url" ]; then
-       ./validation $OCF_RESKEY_keystone_get_token_url $OCF_RESKEY_os_username $OCF_RESKEY_os_tenant_name
-       rc=$?
-       if [ $rc -ne 0 ]; then
-           ocf_log err "Failed to connect to the OpenStack Cinder API (cinder-api): $rc"
-           return $OCF_NOT_RUNNING
-       fi
-    fi
+    # Check the server is listening on the server port
+          engine_db_check=`netstat -an | grep -s "$OCF_RESKEY_console_port" | grep -qs "LISTEN"`
+          rc_db=$?
+          if [ $rc_db -ne 0 ]; then
+              ocf_log err "heat-api is not listening on $OCF_RESKEY_console_port: $rc_db"
+              return $OCF_NOT_RUNNING
+          fi
 
-    ocf_log debug "OpenStack Cinder API (cinder-api) monitor succeeded"
+    ocf_log debug "OpenStack Orchestration Engine (heat-api) monitor succeeded"
     return $OCF_SUCCESS
 }
 
-cinder_api_start() {
+heat_api_start() {
     local rc
 
-    cinder_api_status
+    heat_api_status
     rc=$?
     if [ $rc -eq $OCF_SUCCESS ]; then
-        ocf_log info "OpenStack Cinder API (cinder-api) already running"
+        ocf_log info "OpenStack Orchestration Engine (heat-api) already running"
         return $OCF_SUCCESS
     fi
 
-    # run the actual cinder-api daemon. Don't use ocf_run as we're sending the tool's output
+    # run the actual heat-api daemon. Don't use ocf_run as we're sending the tool's output
     # straight to /dev/null anyway and using ocf_run would break stdout-redirection here.
     su ${OCF_RESKEY_user} -s /bin/sh -c "${OCF_RESKEY_binary} --config-file=$OCF_RESKEY_config \
        $OCF_RESKEY_additional_parameters"' >> /dev/null 2>&1 & echo $!' > $OCF_RESKEY_pid
 
     # Spin waiting for the server to come up.
-    # Let the CRM/LRM time us out if required
     while true; do
-    cinder_api_monitor
+    heat_api_monitor
     rc=$?
     [ $rc -eq $OCF_SUCCESS ] && break
     if [ $rc -ne $OCF_NOT_RUNNING ]; then
-        ocf_log err "OpenStack Cinder API (cinder-api) start failed"
+        ocf_log err "OpenStack Orchestration Engine (heat-api) start failed"
         exit $OCF_ERR_GENERIC
     fi
     sleep 1
     done
 
-    ocf_log info "OpenStack Cinder API (cinder-api) started"
+    ocf_log info "OpenStack Orchestration Engine (heat-api) started"
     return $OCF_SUCCESS
 }
 
-cinder_api_confirm_stop() {
+heat_api_confirm_stop() {
     local my_bin
     local my_processes
 
@@ -306,15 +285,15 @@ cinder_api_confirm_stop() {
     fi
 }
 
-cinder_api_stop() {
+heat_api_stop() {
     local rc
     local pid
 
-    cinder_api_status
+    heat_api_status
     rc=$?
     if [ $rc -eq $OCF_NOT_RUNNING ]; then
-        ocf_log info "OpenStack Cinder API (cinder-api) already stopped"
-        cinder_api_confirm_stop
+        ocf_log info "OpenStack Orchestration Engine (heat-api) already stopped"
+        heat_api_confirm_stop
         return $OCF_SUCCESS
     fi
 
@@ -323,8 +302,8 @@ cinder_api_stop() {
     ocf_run kill -s TERM $pid
     rc=$?
     if [ $rc -ne 0 ]; then
-        ocf_log err "OpenStack Cinder API (cinder-api) couldn't be stopped"
-        cinder_api_confirm_stop
+        ocf_log err "OpenStack Orchestration Engine (heat-api) couldn't be stopped"
+        heat_api_confirm_stop
         exit $OCF_ERR_GENERIC
     fi
 
@@ -335,27 +314,27 @@ cinder_api_stop() {
     fi
     count=0
     while [ $count -lt $shutdown_timeout ]; do
-        cinder_api_status
+        heat_api_status
         rc=$?
         if [ $rc -eq $OCF_NOT_RUNNING ]; then
             break
         fi
         count=`expr $count + 1`
         sleep 1
-        ocf_log debug "OpenStack Cinder API (cinder-api) still hasn't stopped yet. Waiting ..."
+        ocf_log debug "OpenStack Orchestration Engine (heat-api) still hasn't stopped yet. Waiting ..."
     done
 
-    cinder_api_status
+    heat_api_status
     rc=$?
     if [ $rc -ne $OCF_NOT_RUNNING ]; then
         # SIGTERM didn't help either, try SIGKILL
-        ocf_log info "OpenStack Cinder API (cinder-api) failed to stop after ${shutdown_timeout}s \
+        ocf_log info "OpenStack Orchestration Engine (heat-api) failed to stop after ${shutdown_timeout}s \
           using SIGTERM. Trying SIGKILL ..."
         ocf_run kill -s KILL $pid
     fi
-    cinder_api_confirm_stop
+    heat_api_confirm_stop
 
-    ocf_log info "OpenStack Cinder API (cinder-api) stopped"
+    ocf_log info "OpenStack Orchestration Engine (heat-api) stopped"
 
     rm -f $OCF_RESKEY_pid
 
@@ -372,14 +351,14 @@ case "$1" in
 esac
 
 # Anything except meta-data and help must pass validation
-cinder_api_validate || exit $?
+heat_api_validate || exit $?
 
 # What kind of method was invoked?
 case "$1" in
-  start)        cinder_api_start;;
-  stop)         cinder_api_stop;;
-  status)       cinder_api_status;;
-  monitor)      cinder_api_monitor;;
+  start)        heat_api_start;;
+  stop)         heat_api_stop;;
+  status)       heat_api_status;;
+  monitor)      heat_api_monitor;;
   validate-all) ;;
   *)            usage
                 exit $OCF_ERR_UNIMPLEMENTED;;
diff --git a/ocf/keystone b/ocf/keystone
--- a/ocf/keystone
+++ b/ocf/keystone
@@ -12,6 +12,11 @@
 #
 # (c) 2012      hastexo Professional Services GmbH
 #
+# Copyright (c) 2017 Wind River Systems, Inc.
+#
+# SPDX-License-Identifier: Apache-2.0
+#
+#
 # See usage() function below for more details ...
 #
 # OCF instance parameters:
@@ -37,9 +42,9 @@
 
 OCF_RESKEY_binary_default="keystone-all"
 OCF_RESKEY_config_default="/etc/keystone/keystone.conf"
-OCF_RESKEY_pid_default="$HA_RSCTMP/$OCF_RESOURCE_INSTANCE.pid"
+OCF_RESKEY_pid_default="/var/run/openstack-keystone.pid"
 OCF_RESKEY_user_default="keystone"
-OCF_RESKEY_client_binary_default="keystone"
+OCF_RESKEY_client_binary_default="openstack"
 
 : ${OCF_RESKEY_binary=${OCF_RESKEY_binary_default}}
 : ${OCF_RESKEY_config=${OCF_RESKEY_config_default}}
@@ -206,9 +211,10 @@ keystone_validate() {
 keystone_status() {
     local pid
     local rc
-
+	 ocf_log info PID file is $OCF_RESKEY_pid 
     if [ ! -f $OCF_RESKEY_pid ]; then
-        ocf_log info "OpenStack Identity (Keystone) is not running"
+	ocf_log info "pid file not found .."
+    ocf_log info "OpenStack Identity (Keystone) is not running .."
         return $OCF_NOT_RUNNING
     else
     pid=`cat $OCF_RESKEY_pid`
@@ -220,6 +226,7 @@ keystone_status() {
         return $OCF_SUCCESS
     else
         ocf_log info "Old PID file found, but OpenStack Identity (Keystone) is not running"
+        rm -f $OCF_RESKEY_pid
         return $OCF_NOT_RUNNING
     fi
 }
@@ -237,15 +244,13 @@ keystone_monitor() {
 
     # Check whether we are supposed to monitor by logging into Keystone
     # and do it if that's the case.
-    if [ -n "$OCF_RESKEY_client_binary" ] && [ -n "$OCF_RESKEY_os_username" ] \
-    && [ -n "$OCF_RESKEY_os_password" ] && [ -n "$OCF_RESKEY_os_tenant_name" ] \
+    if [ -n "$OCF_RESKEY_client_binary" ] && [ -n "$OCF_RESKEY_os_password" ] && [ -n "$OCF_RESKEY_os_tenant_name" ] \
     && [ -n "$OCF_RESKEY_os_auth_url" ]; then
         ocf_run -q $OCF_RESKEY_client_binary \
         --os-username "$OCF_RESKEY_os_username" \
-        --os-password "$OCF_RESKEY_os_password" \
         --os-tenant-name "$OCF_RESKEY_os_tenant_name" \
         --os-auth-url "$OCF_RESKEY_os_auth_url" \
-        user-list > /dev/null 2>&1
+        user list > /dev/null 2>&1
         rc=$?
         if [ $rc -ne 0 ]; then
             ocf_log err "Failed to connect to the OpenStack Identity (Keystone): $rc"
@@ -265,12 +270,23 @@ keystone_start() {
     if [ $rc -eq $OCF_SUCCESS ]; then
         ocf_log info "OpenStack Identity (Keystone) already running"
         return $OCF_SUCCESS
-    fi
+    fi 
+
+    ocf_log info " pid file -> during start $OCF_RESKEY_pid"
+    ocf_log info "${OCF_RESKEY_user} -s /bin/sh -c ${OCF_RESKEY_binary} \
+      $OCF_RESKEY_additional_parameters"
+
+    # Before starting we need to ensure that orphan workers do not present
+    
+        keystone_confirm_stop
+    #
+ 
 
     # run the actual keystone daemon. Don't use ocf_run as we're sending the tool's output
     # straight to /dev/null anyway and using ocf_run would break stdout-redirection here.
-    su ${OCF_RESKEY_user} -s /bin/sh -c "${OCF_RESKEY_binary} --config-file $OCF_RESKEY_config \
-      $OCF_RESKEY_additional_parameters"' >> /dev/null 2>&1 & echo $!' > $OCF_RESKEY_pid
+
+    su ${OCF_RESKEY_user} -s /bin/sh -c "${OCF_RESKEY_binary}    $OCF_RESKEY_additional_parameters"
+ 
 
     # Spin waiting for the server to come up.
     # Let the CRM/LRM time us out if required
@@ -289,23 +305,60 @@ keystone_start() {
     return $OCF_SUCCESS
 }
 
+keystone_confirm_stop() {
+    local my_bin
+    local my_processes
+    
+    # Enhanced way of finding keytone processes - Process names with  *gunicorn*keysone*
+    my_processes=`pgrep -l -f "^(.*gunicorn.*)(.*keystone.*) ([^\w-]|$)"` 
+
+    if [ -n "${my_processes}" ]
+    then
+        ocf_log info "About to SIGKILL the following: ${my_processes}"
+        pkill -KILL -f "^(.*gunicorn.*)(.*keystone.*) ([^\w-]|$)" ; 
+    fi
+
+}
+
 keystone_stop() {
+
     local rc
     local pid
 
+    # first stop the child process
+    PIDFILE_public="/var/run/resource-agents/openstack-keystone-child.pid"
+    start-stop-daemon --stop --quiet --pidfile $PIDFILE_public
+    RETVAL_public=$?
+    if [ $RETVAL_public -eq 0 ]; then
+        echo "Stopped $DESC_public."
+    else
+        echo "Stopping failed - $PIDFILE_public"
+    fi
+    rm -f $PIDFILE_public
+
+
+
     keystone_status
     rc=$?
+	echo " ret conde 1$rc"
     if [ $rc -eq $OCF_NOT_RUNNING ]; then
         ocf_log info "OpenStack Identity (Keystone) already stopped"
+        keystone_confirm_stop
         return $OCF_SUCCESS
     fi
+
+
+
 
     # Try SIGTERM
     pid=`cat $OCF_RESKEY_pid`
     ocf_run kill -s TERM $pid
+        echo " ret conde 2$rc"
+
     rc=$?
     if [ $rc -ne 0 ]; then
         ocf_log err "OpenStack Identity (Keystone) couldn't be stopped"
+        keystone_confirm_stop
         exit $OCF_ERR_GENERIC
     fi
 
@@ -334,6 +387,7 @@ keystone_stop() {
           using SIGTERM. Trying SIGKILL ..."
         ocf_run kill -s KILL $pid
     fi
+    keystone_confirm_stop
 
     ocf_log info "OpenStack Identity (Keystone) stopped"
 
diff --git a/ocf/neutron-server b/ocf/neutron-server
--- a/ocf/neutron-server
+++ b/ocf/neutron-server
@@ -12,6 +12,10 @@
 # Support:      openstack@lists.launchpad.net
 # License:      Apache Software License (ASL) 2.0
 #
+# Copyright (c) 2014 Wind River Systems, Inc.
+#
+# SPDX-License-Identifier: Apache-2.0
+#
 #
 # See usage() function below for more details ...
 #
@@ -101,7 +105,7 @@ Location of the OpenStack Neutron Server (neutron-server) configuration file
 <content type="string" default="${OCF_RESKEY_config_default}" />
 </parameter>
 
-<parameter name="plugin config" unique="0" required="0">
+<parameter name="plugin_config" unique="0" required="0">
 <longdesc lang="en">
 Location of the OpenStack Default Plugin (Open-vSwitch) configuration file
 </longdesc>
@@ -238,14 +242,13 @@ neutron_server_status() {
         return $OCF_SUCCESS
     else
         ocf_log info "Old PID file found, but OpenStack Neutron Server (neutron-server) is not running"
+        rm -f $OCF_RESKEY_pid
         return $OCF_NOT_RUNNING
     fi
 }
 
 neutron_server_monitor() {
     local rc
-    local token
-    local http_code
 
     neutron_server_status
     rc=$?
@@ -256,18 +259,13 @@ neutron_server_monitor() {
     fi
 
     # Check detailed information about this specific version of the API.
-    if [ -n "$OCF_RESKEY_os_username" ] && [ -n "$OCF_RESKEY_os_password" ] \
-    && [ -n "$OCF_RESKEY_os_tenant_name" ] && [ -n "$OCF_RESKEY_keystone_get_token_url" ]; then
-        token=`curl -s -d  "{\"auth\":{\"passwordCredentials\": {\"username\": \"$OCF_RESKEY_os_username\", \
-          \"password\": \"$OCF_RESKEY_os_password\"}, \"tenantName\": \"$OCF_RESKEY_os_tenant_name\"}}" \
-          -H "Content-type: application/json" $OCF_RESKEY_keystone_get_token_url | tr ',' '\n' | grep '"id":' \
-          | cut -d'"' -f4 | head --lines 1` 
-        http_code=`curl --write-out %{http_code} --output /dev/null -sH "X-Auth-Token: $token" $OCF_RESKEY_url`
-        rc=$?
-        if [ $rc -ne 0 ] || [ $http_code -ne 200 ]; then
-            ocf_log err "Failed to connect to the OpenStack Neutron API (neutron-server): $rc and $http_code"
-            return $OCF_NOT_RUNNING
-        fi
+    if [ -n "$OCF_RESKEY_os_username"] && [ -n "$OCF_RESKEY_os_tenant_name" ] && [ -n "$OCF_RESKEY_keystone_get_token_url" ]; then
+       ./validation $OCF_RESKEY_keystone_get_token_url $OCF_RESKEY_os_username $OCF_RESKEY_os_tenant_name
+       rc=$?
+       if [ $rc -ne 0 ]; then
+           ocf_log err "Failed to connect to the OpenStack Neutron Server (neutron-server): $rc"
+           return $OCF_NOT_RUNNING
+       fi
     fi
 
     ocf_log debug "OpenStack Neutron Server (neutron-server) monitor succeeded"
@@ -288,7 +286,7 @@ neutron_server_start() {
     # Don't use ocf_run as we're sending the tool's output
     # straight to /dev/null anyway and using ocf_run would break stdout-redirection here.
     su ${OCF_RESKEY_user} -s /bin/sh -c "${OCF_RESKEY_binary} --config-file=$OCF_RESKEY_config \
-       	--config-file=$OCF_RESKEY_plugin_config --log-file=/var/log/neutron/server.log $OCF_RESKEY_additional_parameters"' >> \
+       	--config-file=$OCF_RESKEY_plugin_config $OCF_RESKEY_additional_parameters"' >> \
 	/dev/null 2>&1 & echo $!' > $OCF_RESKEY_pid
 
     # Spin waiting for the server to come up.
@@ -308,6 +306,20 @@ neutron_server_start() {
     return $OCF_SUCCESS
 }
 
+neutron_server_confirm_stop() {
+    local my_bin
+    local my_processes
+
+    my_binary=`which ${OCF_RESKEY_binary}`
+    my_processes=`pgrep -l -f "^(python|/usr/bin/python|/usr/bin/python2) ${my_binary}([^\w-]|$)"`
+
+    if [ -n "${my_processes}" ]
+    then
+        ocf_log info "About to SIGKILL the following: ${my_processes}"
+        pkill -KILL -f "^(python|/usr/bin/python|/usr/bin/python2) ${my_binary}([^\w-]|$)"
+    fi
+}
+
 neutron_server_stop() {
     local rc
     local pid
@@ -316,6 +328,7 @@ neutron_server_stop() {
     rc=$?
     if [ $rc -eq $OCF_NOT_RUNNING ]; then
         ocf_log info "OpenStack Neutron Server (neutron-server) already stopped"
+        neutron_server_confirm_stop
         return $OCF_SUCCESS
     fi
 
@@ -325,6 +338,7 @@ neutron_server_stop() {
     rc=$?
     if [ $rc -ne 0 ]; then
         ocf_log err "OpenStack Neutron Server (neutron-server) couldn't be stopped"
+        neutron_server_confirm_stop
         exit $OCF_ERR_GENERIC
     fi
 
@@ -353,6 +367,7 @@ neutron_server_stop() {
           using SIGTERM. Trying SIGKILL ..."
         ocf_run kill -s KILL $pid
     fi
+    neutron_server_confirm_stop
 
     ocf_log info "OpenStack Neutron Server (neutron-server) stopped"
 
diff --git a/ocf/nova-api b/ocf/nova-api
--- a/ocf/nova-api
+++ b/ocf/nova-api
@@ -11,6 +11,10 @@
 # Support:      openstack@lists.launchpad.net
 # License:      Apache Software License (ASL) 2.0
 #
+# Copyright (c) 2014 Wind River Systems, Inc.
+#
+# SPDX-License-Identifier: Apache-2.0
+#
 #
 # See usage() function below for more details ...
 #
@@ -226,14 +230,13 @@ nova_api_status() {
         return $OCF_SUCCESS
     else
         ocf_log info "Old PID file found, but OpenStack Nova API (nova-api) is not running"
+        rm -f $OCF_RESKEY_pid
         return $OCF_NOT_RUNNING
     fi
 }
 
 nova_api_monitor() {
     local rc
-    local token
-    local http_code
 
     nova_api_status
     rc=$?
@@ -244,18 +247,13 @@ nova_api_monitor() {
     fi
 
     # Check detailed information about this specific version of the API.
-    if [ -n "$OCF_RESKEY_os_username" ] && [ -n "$OCF_RESKEY_os_password" ] \
-    && [ -n "$OCF_RESKEY_os_tenant_name" ] && [ -n "$OCF_RESKEY_keystone_get_token_url" ]; then
-        token=`curl -s -d  "{\"auth\":{\"passwordCredentials\": {\"username\": \"$OCF_RESKEY_os_username\", \
-          \"password\": \"$OCF_RESKEY_os_password\"}, \"tenantName\": \"$OCF_RESKEY_os_tenant_name\"}}" \
-          -H "Content-type: application/json" $OCF_RESKEY_keystone_get_token_url | tr ',' '\n' | grep '"id":' \
-          | cut -d'"' -f4 | head --lines 1` 
-        http_code=`curl --write-out %{http_code} --output /dev/null -sH "X-Auth-Token: $token" $OCF_RESKEY_url`
-        rc=$?
-        if [ $rc -ne 0 ] || [ $http_code -ne 200 ]; then
-            ocf_log err "Failed to connect to the OpenStack Nova API (nova-api): $rc and $http_code"
-            return $OCF_NOT_RUNNING
-        fi
+    if [ -n "$OCF_RESKEY_os_username"] && [ -n "$OCF_RESKEY_os_tenant_name" ] && [ -n "$OCF_RESKEY_keystone_get_token_url" ]; then
+       ./validation $OCF_RESKEY_keystone_get_token_url $OCF_RESKEY_os_username $OCF_RESKEY_os_tenant_name
+       rc=$?
+       if [ $rc -ne 0 ]; then
+           ocf_log err "Failed to connect to the OpenStack Nova API (nova-api): $rc"
+           return $OCF_NOT_RUNNING
+       fi
     fi
 
     ocf_log debug "OpenStack Nova API (nova-api) monitor succeeded"
@@ -271,6 +269,12 @@ nova_api_start() {
         ocf_log info "OpenStack Nova API (nova-api) already running"
         return $OCF_SUCCESS
     fi
+
+    # Change the working dir to /, to be sure it's accesible
+    cd /
+
+    # Run the pre-start hooks.  This can be used to trigger a nova database sync, for example.
+    /usr/bin/nova-controller-runhooks
 
     # run the actual nova-api daemon. Don't use ocf_run as we're sending the tool's output
     # straight to /dev/null anyway and using ocf_run would break stdout-redirection here.
@@ -294,6 +298,20 @@ nova_api_start() {
     return $OCF_SUCCESS
 }
 
+nova_api_confirm_stop() {
+    local my_bin
+    local my_processes
+
+    my_binary=`which ${OCF_RESKEY_binary}`
+    my_processes=`pgrep -l -f "^(python|/usr/bin/python|/usr/bin/python2) ${my_binary}([^\w-]|$)"`
+
+    if [ -n "${my_processes}" ]
+    then
+        ocf_log info "About to SIGKILL the following: ${my_processes}"
+        pkill -KILL -f "^(python|/usr/bin/python|/usr/bin/python2) ${my_binary}([^\w-]|$)"
+    fi
+}
+
 nova_api_stop() {
     local rc
     local pid
@@ -302,6 +320,7 @@ nova_api_stop() {
     rc=$?
     if [ $rc -eq $OCF_NOT_RUNNING ]; then
         ocf_log info "OpenStack Nova API (nova-api) already stopped"
+        nova_api_confirm_stop
         return $OCF_SUCCESS
     fi
 
@@ -311,6 +330,7 @@ nova_api_stop() {
     rc=$?
     if [ $rc -ne 0 ]; then
         ocf_log err "OpenStack Nova API (nova-api) couldn't be stopped"
+        nova_api_confirm_stop
         exit $OCF_ERR_GENERIC
     fi
 
@@ -339,6 +359,7 @@ nova_api_stop() {
           using SIGTERM. Trying SIGKILL ..."
         ocf_run kill -s KILL $pid
     fi
+    nova_api_confirm_stop
 
     ocf_log info "OpenStack Nova API (nova-api) stopped"
 
diff --git a/ocf/nova-compute b/ocf/nova-compute
--- a/ocf/nova-compute
+++ b/ocf/nova-compute
@@ -1,9 +1,9 @@
 #!/bin/sh
 #
 #
-# OpenStack Cinder Scheduler Service (cinder-schedule)
+# OpenStack Bare Metal Provisioning Service Compute Service (nova-compute)
 #
-# Description: Manages an OpenStack Cinder Scheduler Service (cinder-schedule) process as an HA resource
+# Description: Manages an OpenStack Bare Metal Provisioning Service Compute Service (nova-compute) process as an HA resource
 #
 # Authors: Emilien Macchi
 # Mainly inspired by the Nova Scheduler resource agent written by Sebastien Han
@@ -11,7 +11,7 @@
 # Support: openstack@lists.launchpad.net
 # License: Apache Software License (ASL) 2.0
 #
-# Copyright (c) 2014 Wind River Systems, Inc.
+# Copyright (c) 2017 Wind River Systems, Inc.
 #
 # SPDX-License-Identifier: Apache-2.0
 #
@@ -31,14 +31,15 @@
 
 : ${OCF_FUNCTIONS_DIR=${OCF_ROOT}/lib/heartbeat}
 . ${OCF_FUNCTIONS_DIR}/ocf-shellfuncs
+. /usr/bin/tsconfig
 
 #######################################################################
 
 # Fill in some defaults if no values are specified
 
-OCF_RESKEY_binary_default="cinder-scheduler"
-OCF_RESKEY_config_default="/etc/cinder/cinder.conf"
-OCF_RESKEY_user_default="cinder"
+OCF_RESKEY_binary_default="nova-compute"
+OCF_RESKEY_config_default="/etc/nova/nova-ironic.conf"
+OCF_RESKEY_user_default="nova"
 OCF_RESKEY_pid_default="$HA_RSCTMP/$OCF_RESOURCE_INSTANCE.pid"
 OCF_RESKEY_amqp_server_port_default="5672"
 
@@ -54,7 +55,7 @@ usage() {
     cat <<UEND
         usage: $0 (start|stop|validate-all|meta-data|status|monitor)
 
-        $0 manages an OpenStack Cinder Scheduler Service (cinder-schedule) process as an HA resource
+        $0 manages an OpenStack Bare Metal Provisioning Service Compute Service (nova-compute) process as an HA resource
 
         The 'start' operation starts the scheduler service.
         The 'stop' operation stops the scheduler service.
@@ -70,46 +71,46 @@ meta_data() {
     cat <<END
 <?xml version="1.0"?>
 <!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
-<resource-agent name="cinder-schedule">
+<resource-agent name="nova-compute">
 <version>1.0</version>
 
 <longdesc lang="en">
-Resource agent for the OpenStack Cinder Scheduler Service (cinder-schedule)
-May manage a cinder-schedule instance or a clone set that
-creates a distributed cinder-schedule cluster.
+Resource agent for the OpenStack Bare Metal Provisioning Service Compute Service (nova-compute)
+May manage a nova-compute instance or a clone set that
+creates a distributed nova-compute cluster.
 </longdesc>
-<shortdesc lang="en">Manages the OpenStack Cinder Scheduler Service (cinder-schedule)</shortdesc>
+<shortdesc lang="en">Manages the OpenStack Bare Metal Provisioning Service Compute Service (nova-compute)</shortdesc>
 <parameters>
 
 <parameter name="binary" unique="0" required="0">
 <longdesc lang="en">
-Location of the OpenStack Cinder Scheduler server binary (cinder-schedule)
+Location of the OpenStack Bare Metal Provisioning Service Compute server binary (nova-compute)
 </longdesc>
-<shortdesc lang="en">OpenStack Cinder Scheduler server binary (cinder-schedule)</shortdesc>
+<shortdesc lang="en">OpenStack Bare Metal Provisioning Service Compute server binary (nova-compute)</shortdesc>
 <content type="string" default="${OCF_RESKEY_binary_default}" />
 </parameter>
 
 <parameter name="config" unique="0" required="0">
 <longdesc lang="en">
-Location of the OpenStack Cinder Scheduler Service (cinder-schedule) configuration file
+Location of the OpenStack Bare Metal Provisioning Service Compute Service (nova-compute) configuration file
 </longdesc>
-<shortdesc lang="en">OpenStack Cinder Scheduler (cinder-schedule registry) config file</shortdesc>
+<shortdesc lang="en">OpenStack Bare Metal Provisioning Service Compute (nova-compute registry) config file</shortdesc>
 <content type="string" default="${OCF_RESKEY_config_default}" />
 </parameter>
 
 <parameter name="user" unique="0" required="0">
 <longdesc lang="en">
-User running OpenStack Cinder Scheduler Service (cinder-schedule)
+User running OpenStack Bare Metal Provisioning Service Compute Service (nova-compute)
 </longdesc>
-<shortdesc lang="en">OpenStack Cinder Scheduler Service (cinder-schedule) user</shortdesc>
+<shortdesc lang="en">OpenStack Bare Metal Provisioning Service Compute Service (nova-compute) user</shortdesc>
 <content type="string" default="${OCF_RESKEY_user_default}" />
 </parameter>
 
 <parameter name="pid" unique="0" required="0">
 <longdesc lang="en">
-The pid file to use for this OpenStack Cinder Scheduler Service (cinder-schedule) instance
+The pid file to use for this OpenStack Bare Metal Provisioning Service Compute Service (nova-compute) instance
 </longdesc>
-<shortdesc lang="en">OpenStack Cinder Scheduler Service (cinder-schedule) pid file</shortdesc>
+<shortdesc lang="en">OpenStack Bare Metal Provisioning Service Compute Service (nova-compute) pid file</shortdesc>
 <content type="string" default="${OCF_RESKEY_pid_default}" />
 </parameter>
 
@@ -124,9 +125,9 @@ The listening port number of the AMQP server. Use for monitoring purposes
 
 <parameter name="additional_parameters" unique="0" required="0">
 <longdesc lang="en">
-Additional parameters to pass on to the OpenStack Cinder Scheduler Service (cinder-schedule)
+Additional parameters to pass on to the OpenStack Bare Metal Provisioning Service Compute Service (nova-compute)
 </longdesc>
-<shortdesc lang="en">Additional parameters for cinder-schedule</shortdesc>
+<shortdesc lang="en">Additional parameters for nova-compute</shortdesc>
 <content type="string" />
 </parameter>
 
@@ -147,7 +148,7 @@ END
 #######################################################################
 # Functions invoked by resource manager actions
 
-cinder_scheduler_check_port() {
+nova_compute_check_port() {
 # This function has been taken from the squid RA and improved a bit
 # The length of the integer must be 4
 # Examples of valid port: "1080", "0080"
@@ -155,7 +156,7 @@ cinder_scheduler_check_port() {
 
     local int
     local cnt
-    
+
     int="$1"
     cnt=${#int}
     echo $int |egrep -qx '[0-9]+(:[0-9]+)?(,[0-9]+(:[0-9]+)?)*'
@@ -166,13 +167,13 @@ cinder_scheduler_check_port() {
     fi
 }
 
-cinder_scheduler_validate() {
+nova_compute_validate() {
     local rc
 
     check_binary $OCF_RESKEY_binary
     check_binary netstat
-    cinder_scheduler_check_port $OCF_RESKEY_amqp_server_port
-    
+    nova_compute_check_port $OCF_RESKEY_amqp_server_port
+
     # A config file on shared storage that is not available
     # during probes is OK.
     if [ ! -f $OCF_RESKEY_config ]; then
@@ -193,12 +194,12 @@ cinder_scheduler_validate() {
     true
 }
 
-cinder_scheduler_status() {
+nova_compute_status() {
     local pid
     local rc
 
     if [ ! -f $OCF_RESKEY_pid ]; then
-        ocf_log info "OpenStack Cinder Scheduler (cinder-schedule) is not running"
+        ocf_log info "OpenStack Bare Metal Provisioning Service Compute (nova-compute) is not running"
         return $OCF_NOT_RUNNING
     else
         pid=`cat $OCF_RESKEY_pid`
@@ -209,18 +210,18 @@ cinder_scheduler_status() {
     if [ $rc -eq 0 ]; then
         return $OCF_SUCCESS
     else
-        ocf_log info "Old PID file found, but OpenStack Cinder Scheduler (cinder-schedule) is not running"
+        ocf_log info "Old PID file found, but OpenStack Bare Metal Provisioning Service Compute (nova-compute) is not running"
         rm -f $OCF_RESKEY_pid
         return $OCF_NOT_RUNNING
     fi
 }
 
-cinder_scheduler_monitor() {
+nova_compute_monitor() {
     local rc
     local pid
     local scheduler_amqp_check
 
-    cinder_scheduler_status
+    nova_compute_status
     rc=$?
 
     # If status returned anything but success, return that immediately
@@ -228,52 +229,42 @@ cinder_scheduler_monitor() {
         return $rc
     fi
 
-    # Check the connections according to the PID.
-    # We are sure to hit the scheduler process and not other Cinder process with the same connection behavior (for example cinder-api)
-        pid=`cat $OCF_RESKEY_pid`
-        scheduler_amqp_check=`netstat -punt | grep -s "$OCF_RESKEY_amqp_server_port" | grep -s "$pid" | grep -qs "ESTABLISHED"`
-        rc=$?
-        if [ $rc -ne 0 ]; then
-        ocf_log err "Cinder Scheduler is not connected to the AMQP server : $rc"
-        return $OCF_NOT_RUNNING
-        fi
-
-    ocf_log debug "OpenStack Cinder Scheduler (cinder-schedule) monitor succeeded"
+    ocf_log debug "OpenStack Bare Metal Provisioning Service Compute (nova-compute) monitor succeeded"
     return $OCF_SUCCESS
 }
 
-cinder_scheduler_start() {
+nova_compute_start() {
     local rc
 
-    cinder_scheduler_status
+    nova_compute_status
     rc=$?
     if [ $rc -eq $OCF_SUCCESS ]; then
-        ocf_log info "OpenStack Cinder Scheduler (cinder-schedule) already running"
+        ocf_log info "OpenStack Bare Metal Provisioning Service Compute (nova-compute) already running"
         return $OCF_SUCCESS
     fi
 
-    # run the actual cinder-schedule daemon. Don't use ocf_run as we're sending the tool's output
+    # run the actual nova-compute daemon. Don't use ocf_run as we're sending the tool's output
     # straight to /dev/null anyway and using ocf_run would break stdout-redirection here.
     su ${OCF_RESKEY_user} -s /bin/sh -c "${OCF_RESKEY_binary} --config-file=$OCF_RESKEY_config \
        $OCF_RESKEY_additional_parameters"' >> /dev/null 2>&1 & echo $!' > $OCF_RESKEY_pid
 
     # Spin waiting for the server to come up.
     while true; do
-    cinder_scheduler_monitor
+    nova_compute_monitor
     rc=$?
     [ $rc -eq $OCF_SUCCESS ] && break
     if [ $rc -ne $OCF_NOT_RUNNING ]; then
-        ocf_log err "OpenStack Cinder Scheduler (cinder-schedule) start failed"
+        ocf_log err "OpenStack Bare Metal Provisioning Service Compute (nova-compute) start failed"
         exit $OCF_ERR_GENERIC
     fi
     sleep 1
     done
 
-    ocf_log info "OpenStack Cinder Scheduler (cinder-schedule) started"
+    ocf_log info "OpenStack Bare Metal Provisioning Service Compute (nova-compute) started"
     return $OCF_SUCCESS
 }
 
-cinder_scheduler_confirm_stop() {
+nova_compute_confirm_stop() {
     local my_bin
     local my_processes
 
@@ -287,15 +278,15 @@ cinder_scheduler_confirm_stop() {
     fi
 }
 
-cinder_scheduler_stop() {
+nova_compute_stop() {
     local rc
     local pid
 
-    cinder_scheduler_status
+    nova_compute_status
     rc=$?
     if [ $rc -eq $OCF_NOT_RUNNING ]; then
-        ocf_log info "OpenStack Cinder Scheduler (cinder-schedule) already stopped"
-        cinder_scheduler_confirm_stop
+        ocf_log info "OpenStack Bare Metal Provisioning Service Compute (nova-compute) already stopped"
+        nova_compute_confirm_stop
         return $OCF_SUCCESS
     fi
 
@@ -304,39 +295,39 @@ cinder_scheduler_stop() {
     ocf_run kill -s TERM $pid
     rc=$?
     if [ $rc -ne 0 ]; then
-        ocf_log err "OpenStack Cinder Scheduler (cinder-schedule) couldn't be stopped"
-        cinder_scheduler_confirm_stop
+        ocf_log err "OpenStack Bare Metal Provisioning Service Compute (nova-compute) couldn't be stopped"
+        nova_compute_confirm_stop
         exit $OCF_ERR_GENERIC
     fi
 
     # stop waiting
-    shutdown_timeout=15
+    shutdown_timeout=2
     if [ -n "$OCF_RESKEY_CRM_meta_timeout" ]; then
         shutdown_timeout=$((($OCF_RESKEY_CRM_meta_timeout/1000)-5))
     fi
     count=0
     while [ $count -lt $shutdown_timeout ]; do
-        cinder_scheduler_status
+        nova_compute_status
         rc=$?
         if [ $rc -eq $OCF_NOT_RUNNING ]; then
             break
         fi
         count=`expr $count + 1`
         sleep 1
-        ocf_log debug "OpenStack Cinder Scheduler (cinder-schedule) still hasn't stopped yet. Waiting ..."
+        ocf_log debug "OpenStack Bare Metal Provisioning Service Compute (nova-compute) still hasn't stopped yet. Waiting ..."
     done
 
-    cinder_scheduler_status
+    nova_compute_status
     rc=$?
     if [ $rc -ne $OCF_NOT_RUNNING ]; then
         # SIGTERM didn't help either, try SIGKILL
-        ocf_log info "OpenStack Cinder Scheduler (cinder-schedule) failed to stop after ${shutdown_timeout}s \
+        ocf_log info "OpenStack Bare Metal Provisioning Service Compute (nova-compute) failed to stop after ${shutdown_timeout}s \
           using SIGTERM. Trying SIGKILL ..."
         ocf_run kill -s KILL $pid
     fi
-    cinder_scheduler_confirm_stop
+    nova_compute_confirm_stop
 
-    ocf_log info "OpenStack Cinder Scheduler (cinder-schedule) stopped"
+    ocf_log info "OpenStack Bare Metal Provisioning Service Compute (nova-compute) stopped"
 
     rm -f $OCF_RESKEY_pid
 
@@ -353,15 +344,16 @@ case "$1" in
 esac
 
 # Anything except meta-data and help must pass validation
-cinder_scheduler_validate || exit $?
+nova_compute_validate || exit $?
 
 # What kind of method was invoked?
 case "$1" in
-  start) cinder_scheduler_start;;
-  stop) cinder_scheduler_stop;;
-  status) cinder_scheduler_status;;
-  monitor) cinder_scheduler_monitor;;
+  start) nova_compute_start;;
+  stop) nova_compute_stop;;
+  status) nova_compute_status;;
+  monitor) nova_compute_monitor;;
   validate-all) ;;
   *) usage
                 exit $OCF_ERR_UNIMPLEMENTED;;
 esac
+
diff --git a/ocf/nova-serialproxy b/ocf/nova-serialproxy
--- a/ocf/nova-serialproxy
+++ b/ocf/nova-serialproxy
@@ -1,17 +1,17 @@
 #!/bin/sh
 #
 #
-# OpenStack Nova VNC Console (nova-novncproxy)
+# OpenStack Nova Serial Console (nova-serialproxy)
 #
-# Description:  Manages an OpenStack Nova VNC Console (nova-novncproxy) process as an HA resource
+# Description:  Manages an OpenStack Nova Serialproxy (nova-serialproxy) process as an HA resource
 #
 # Authors:      Sébastien Han
-# Mainly inspired by the Glance API resource agent written by Martin Gerhard Loschwitz from Hastexo: http://goo.gl/whLpr
+# Mainly inspired by the novnc API resource agent written by Martin Gerhard Loschwitz from Hastexo: http://goo.gl/whLpr
 #
 # Support:      openstack@lists.launchpad.net
 # License:      Apache Software License (ASL) 2.0
 #
-# Copyright (c) 2014 Wind River Systems, Inc.
+# Copyright (c) 2018 Wind River Systems, Inc.
 #
 # SPDX-License-Identifier: Apache-2.0
 #
@@ -24,7 +24,6 @@
 #   OCF_RESKEY_user
 #   OCF_RESKEY_pid
 #   OCF_RESKEY_console_port
-#   OCF_RESKEY_web
 #   OCF_RESKEY_additional_parameters
 #######################################################################
 # Initialization:
@@ -36,19 +35,17 @@
 
 # Fill in some defaults if no values are specified
 
-OCF_RESKEY_binary_default="nova-novncproxy"
-OCF_RESKEY_config_default="/etc/nova/nova.conf"
+OCF_RESKEY_binary_default="nova-serialproxy"
+OCF_RESKEY_config_default="/etc/nova/nova-ironic.conf"
 OCF_RESKEY_user_default="nova"
 OCF_RESKEY_pid_default="$HA_RSCTMP/$OCF_RESOURCE_INSTANCE.pid"
-OCF_RESKEY_console_port_default="6080"
-OCF_RESKEY_web_default="/usr/share/novnc/"
+OCF_RESKEY_console_port_default="6083"
 
 : ${OCF_RESKEY_binary=${OCF_RESKEY_binary_default}}
 : ${OCF_RESKEY_config=${OCF_RESKEY_config_default}}
 : ${OCF_RESKEY_user=${OCF_RESKEY_user_default}}
 : ${OCF_RESKEY_pid=${OCF_RESKEY_pid_default}}
 : ${OCF_RESKEY_console_port=${OCF_RESKEY_console_port_default}}
-: ${OCF_RESKEY_web=${OCF_RESKEY_web_default}}
 
 #######################################################################
 
@@ -56,7 +53,7 @@ usage() {
     cat <<UEND
         usage: $0 (start|stop|validate-all|meta-data|status|monitor)
 
-        $0 manages an OpenStack Nova VNC Console (nova-novncproxy) process as an HA resource 
+        $0 manages an OpenStack Nova Serial proxy (nova-serialproxy) process as an HA resource 
 
         The 'start' operation starts the console service.
         The 'stop' operation stops the console service.
@@ -72,70 +69,62 @@ meta_data() {
     cat <<END
 <?xml version="1.0"?>
 <!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
-<resource-agent name="nova-novncproxy">
+<resource-agent name="nova-serialproxy">
 <version>1.0</version>
 
 <longdesc lang="en">
-Resource agent for the OpenStack Nova VNC Console Service (nova-novncproxy)
-May manage a nova-novncproxy instance or a clone set that 
-creates a distributed nova-novncproxy cluster.
+Resource agent for the OpenStack Nova Serialproxy Service (nova-serialproxy)
+May manage a nova-serialproxy instance or a clone set that 
+creates a distributed nova-serialproxy cluster.
 </longdesc>
-<shortdesc lang="en">Manages the OpenStack Nova VNC Console (nova-novncproxy)</shortdesc>
+<shortdesc lang="en">Manages the OpenStack Nova Serial Console (nova-serialproxy)</shortdesc>
 <parameters>
 
 <parameter name="binary" unique="0" required="0">
 <longdesc lang="en">
-Location of the OpenStack Nova VNC Console server binary (nova-novncproxy)
+Location of the OpenStack Nova Serial Console server binary (nova-serialproxy)
 </longdesc>
-<shortdesc lang="en">OpenStack Nova VNC Console server binary (nova-novncproxy)</shortdesc>
+<shortdesc lang="en">OpenStack Nova Serial Console server binary (nova-serialproxy)</shortdesc>
 <content type="string" default="${OCF_RESKEY_binary_default}" />
 </parameter>
 
 <parameter name="config" unique="0" required="0">
 <longdesc lang="en">
-Location of the OpenStack Nova VNC Console (nova-novncproxy) configuration file
+Location of the OpenStack Nova Serial Console (nova-serialproxy) configuration file
 </longdesc>
-<shortdesc lang="en">OpenStack Nova VNC Console (nova-novncproxy registry) config file</shortdesc>
+<shortdesc lang="en">OpenStack Nova Serial Console (nova-serialproxy registry) config file</shortdesc>
 <content type="string" default="${OCF_RESKEY_config_default}" />
 </parameter>
 
 <parameter name="user" unique="0" required="0">
 <longdesc lang="en">
-User running OpenStack Nova VNC Console (nova-novncproxy)
+User running OpenStack Nova Serial proxy (nova-serialproxy)
 </longdesc>
-<shortdesc lang="en">OpenStack Nova VNC Console (nova-novncproxy) user</shortdesc>
+<shortdesc lang="en">OpenStack Nova Serialproxy (nova-serialproxy) user</shortdesc>
 <content type="string" default="${OCF_RESKEY_user_default}" />
 </parameter>
 
 <parameter name="console_port" unique="0" required="0">
 <longdesc lang="en">
-VNC console type running: nova-novnc
+Serial console type running: nova-serialproxy
 </longdesc>
-<shortdesc lang="en">OpenStack Nova VNC Console (nova-novncproxy) console type</shortdesc>
+<shortdesc lang="en">OpenStack Nova Serial Console (nova-serialproxy) console type</shortdesc>
 <content type="integer" default="${OCF_RESKEY_console_port_default}" />
-</parameter>
-
-<parameter name="web" unique="0" required="0">
-<longdesc lang="en">
-VNC console web URL
-</longdesc>
-<shortdesc lang="en">OpenStack Nova VNC Console (nova-novncproxy) web URL</shortdesc>
-<content type="string" default="${OCF_RESKEY_web_default}" />
 </parameter>
 
 <parameter name="pid" unique="0" required="0">
 <longdesc lang="en">
-The pid file to use for this OpenStack Nova VNC Console (nova-novncproxy) instance
+The pid file to use for this OpenStack Nova Serial Console (nova-serialproxy) instance
 </longdesc>
-<shortdesc lang="en">OpenStack Nova VNC Console (nova-novncproxy) pid file</shortdesc>
+<shortdesc lang="en">OpenStack Nova VNC Console (nova-serialproxy) pid file</shortdesc>
 <content type="string" default="${OCF_RESKEY_pid_default}" />
 </parameter>
 
 <parameter name="additional_parameters" unique="0" required="0">
 <longdesc lang="en">
-Additional parameters to pass on to the OpenStack Nova VNC Console (nova-novncproxy)
+Additional parameters to pass on to the OpenStack Nova Serialproxy (nova-serialproxy)
 </longdesc>
-<shortdesc lang="en">Additional parameters for nova-novncproxy</shortdesc>
+<shortdesc lang="en">Additional parameters for nova-serialproxy</shortdesc>
 <content type="string" />
 </parameter>
 
@@ -156,7 +145,7 @@ END
 #######################################################################
 # Functions invoked by resource manager actions
 
-nova_vnc_console_validate() {
+nova_serial_console_validate() {
     local rc
 
     check_binary $OCF_RESKEY_binary
@@ -182,12 +171,12 @@ nova_vnc_console_validate() {
     true
 }
 
-nova_vnc_console_status() {
+nova_serial_console_status() {
     local pid
     local rc
 
     if [ ! -f $OCF_RESKEY_pid ]; then
-        ocf_log info "OpenStack Nova VNC Console (nova-novncproxy) is not running"
+        ocf_log info "OpenStack Nova Serialproxy (nova-serialproxy) is not running"
         return $OCF_NOT_RUNNING
     else
         pid=`cat $OCF_RESKEY_pid`
@@ -198,17 +187,17 @@ nova_vnc_console_status() {
     if [ $rc -eq 0 ]; then
         return $OCF_SUCCESS
     else
-        ocf_log info "Old PID file found, but OpenStack Nova VNC Console (nova-novncproxy) is not running"
+        ocf_log info "Old PID file found, but OpenStack Nova Serialproxy (nova-serialproxy) is not running"
         rm -f $OCF_RESKEY_pid
         return $OCF_NOT_RUNNING
     fi
 }
 
-nova_vnc_console_monitor() {
+nova_serial_console_monitor() {
     local rc
-    local vnc_list_check
+    local serial_list_check
 
-    nova_vnc_console_status
+    nova_serial_console_status
     rc=$?
 
     # If status returned anything but success, return that immediately
@@ -216,56 +205,56 @@ nova_vnc_console_monitor() {
         return $rc
     fi
 
-    # Check whether we are supposed to monitor by logging into nova-novncproxy
+    # Check whether we are supposed to monitor by logging into nova-serialproxy
     # and do it if that's the case.
     # Adding -n to netstat so that dns delays will not impact this.
-	vnc_list_check=`netstat -an | grep -s "$OCF_RESKEY_console_port" | grep -qs "LISTEN"`
+	serial_list_check=`netstat -an | grep -s "$OCF_RESKEY_console_port" | grep -qs "LISTEN"`
     rc=$?
     if [ $rc -ne 0 ]; then
-        ocf_log err "Nova VNC Console doesn't seem to listen on his default port: $rc"
+        ocf_log err "Nova Serial Console doesn't seem to listen on his default port: $rc"
         return $OCF_NOT_RUNNING
     fi
 
-    ocf_log debug "OpenStack Nova VNC Console (nova-novncproxy) monitor succeeded"
+    ocf_log debug "OpenStack Nova Serial Console (nova-serialproxy) monitor succeeded"
     return $OCF_SUCCESS
 }
 
-nova_vnc_console_start() {
+nova_serial_console_start() {
     local rc
 
-    nova_vnc_console_status
+    nova_serial_console_status
     rc=$?
     if [ $rc -eq $OCF_SUCCESS ]; then
-        ocf_log info "OpenStack Nova VNC Console (nova-novncproxy) already running"
+        ocf_log info "OpenStack Nova Serial Console (nova-serialproxy) already running"
         return $OCF_SUCCESS
     fi
 
     # Change the working dir to /, to be sure it's accesible
     cd /
 
-    # run the actual nova-novncproxy daemon. Don't use ocf_run as we're sending the tool's output
+    # run the actual nova-serialproxy daemon. Don't use ocf_run as we're sending the tool's output
     # straight to /dev/null anyway and using ocf_run would break stdout-redirection here.
-    su ${OCF_RESKEY_user} -s /bin/sh -c "${OCF_RESKEY_binary} --config-file=$OCF_RESKEY_config --web /usr/share/novnc/ \
+    su ${OCF_RESKEY_user} -s /bin/sh -c "${OCF_RESKEY_binary} --config-file=$OCF_RESKEY_config \
        $OCF_RESKEY_additional_parameters"' >> /dev/null 2>&1 & echo $!' > $OCF_RESKEY_pid
 
     # Spin waiting for the server to come up.
     # Let the CRM/LRM time us out if required
     while true; do
-    nova_vnc_console_monitor
+    nova_serial_console_monitor
     rc=$?
     [ $rc -eq $OCF_SUCCESS ] && break
     if [ $rc -ne $OCF_NOT_RUNNING ]; then
-        ocf_log err "OpenStack Nova VNC Console (nova-novncproxy) start failed"
+        ocf_log err "OpenStack Nova Serial Console (nova-serialproxy) start failed"
         exit $OCF_ERR_GENERIC
     fi
     sleep 1
     done
 
-    ocf_log info "OpenStack Nova VNC Console (nova-novncproxy) started"
+    ocf_log info "OpenStack Nova Serial Console (nova-serialproxy) started"
     return $OCF_SUCCESS
 }
 
-nova_vnc_console_confirm_stop() {
+nova_serial_console_confirm_stop() {
     local my_bin
     local my_processes
 
@@ -279,15 +268,15 @@ nova_vnc_console_confirm_stop() {
     fi
 }
 
-nova_vnc_console_stop() {
+nova_serial_console_stop() {
     local rc
     local pid
 
-    nova_vnc_console_status
+    nova_serial_console_status
     rc=$?
     if [ $rc -eq $OCF_NOT_RUNNING ]; then
-        ocf_log info "OpenStack Nova VNC Console (nova-novncproxy) already stopped"
-        nova_vnc_console_confirm_stop
+        ocf_log info "OpenStack Nova Serial Console (nova-serialproxy) already stopped"
+        nova_serial_console_confirm_stop
         return $OCF_SUCCESS
     fi
 
@@ -296,8 +285,8 @@ nova_vnc_console_stop() {
     ocf_run kill -s TERM $pid
     rc=$?
     if [ $rc -ne 0 ]; then
-        ocf_log err "OpenStack Nova VNC Console (nova-novncproxy) couldn't be stopped"
-        nova_vnc_console_confirm_stop
+        ocf_log err "OpenStack Nova Serial Console (nova-serialproxy) couldn't be stopped"
+        nova_serial_console_confirm_stop
         exit $OCF_ERR_GENERIC
     fi
 
@@ -308,27 +297,27 @@ nova_vnc_console_stop() {
     fi
     count=0
     while [ $count -lt $shutdown_timeout ]; do
-        nova_vnc_console_status
+        nova_serial_console_status
         rc=$?
         if [ $rc -eq $OCF_NOT_RUNNING ]; then
             break
         fi
         count=`expr $count + 1`
         sleep 1
-        ocf_log debug "OpenStack Nova VNC Console (nova-novncproxy) still hasn't stopped yet. Waiting ..."
+        ocf_log debug "OpenStack Nova Serial Console (nova-serialproxy) still hasn't stopped yet. Waiting ..."
     done
 
-    nova_vnc_console_status
+    nova_serial_console_status
     rc=$?
     if [ $rc -ne $OCF_NOT_RUNNING ]; then
         # SIGTERM didn't help either, try SIGKILL
-        ocf_log info "OpenStack Nova VNC Console (nova-novncproxy) failed to stop after ${shutdown_timeout}s \
+        ocf_log info "OpenStack Nova Serial Console (nova-serialproxy) failed to stop after ${shutdown_timeout}s \
           using SIGTERM. Trying SIGKILL ..."
         ocf_run kill -s KILL $pid
     fi
-    nova_vnc_console_confirm_stop
+    nova_serial_console_confirm_stop
 
-    ocf_log info "OpenStack Nova VNC Console (nova-novncproxy) stopped"
+    ocf_log info "OpenStack Nova Serial Console (nova-serialproxy) stopped"
 
     rm -f $OCF_RESKEY_pid
 
@@ -345,14 +334,14 @@ case "$1" in
 esac
 
 # Anything except meta-data and help must pass validation
-nova_vnc_console_validate || exit $?
+nova_serial_console_validate || exit $?
 
 # What kind of method was invoked?
 case "$1" in
-  start)        nova_vnc_console_start;;
-  stop)         nova_vnc_console_stop;;
-  status)       nova_vnc_console_status;;
-  monitor)      nova_vnc_console_monitor;;
+  start)        nova_serial_console_start;;
+  stop)         nova_serial_console_stop;;
+  status)       nova_serial_console_status;;
+  monitor)      nova_serial_console_monitor;;
   validate-all) ;;
   *)            usage
                 exit $OCF_ERR_UNIMPLEMENTED;;
diff --git a/ocf/panko-api b/ocf/panko-api
--- a/ocf/panko-api
+++ b/ocf/panko-api
@@ -1,17 +1,13 @@
 #!/bin/sh
 #
 #
-# OpenStack Cinder Scheduler Service (cinder-schedule)
+# OpenStack Panko API Service (panko-api)
 #
-# Description: Manages an OpenStack Cinder Scheduler Service (cinder-schedule) process as an HA resource
+# Description:  Manages an OpenStack Panko API Service (panko-api) process as an HA resource
 #
-# Authors: Emilien Macchi
-# Mainly inspired by the Nova Scheduler resource agent written by Sebastien Han
+# License:      Apache Software License (ASL) 2.0
 #
-# Support: openstack@lists.launchpad.net
-# License: Apache Software License (ASL) 2.0
-#
-# Copyright (c) 2014 Wind River Systems, Inc.
+# Copyright (c) 2017 Wind River Systems, Inc.
 #
 # SPDX-License-Identifier: Apache-2.0
 #
@@ -19,13 +15,13 @@
 # See usage() function below for more details ...
 #
 # OCF instance parameters:
-# OCF_RESKEY_binary
-# OCF_RESKEY_config
-# OCF_RESKEY_user
-# OCF_RESKEY_pid
-# OCF_RESKEY_monitor_binary
-# OCF_RESKEY_amqp_server_port
-# OCF_RESKEY_additional_parameters
+#   OCF_RESKEY_binary
+#   OCF_RESKEY_config
+#   OCF_RESKEY_user
+#   OCF_RESKEY_pid
+#   OCF_RESKEY_monitor_binary
+#   OCF_RESKEY_server_port
+#   OCF_RESKEY_additional_parameters
 #######################################################################
 # Initialization:
 
@@ -36,17 +32,17 @@
 
 # Fill in some defaults if no values are specified
 
-OCF_RESKEY_binary_default="cinder-scheduler"
-OCF_RESKEY_config_default="/etc/cinder/cinder.conf"
-OCF_RESKEY_user_default="cinder"
+OCF_RESKEY_binary_default="panko-api"
+OCF_RESKEY_config_default="/etc/panko/panko.conf"
+OCF_RESKEY_user_default="root"
 OCF_RESKEY_pid_default="$HA_RSCTMP/$OCF_RESOURCE_INSTANCE.pid"
-OCF_RESKEY_amqp_server_port_default="5672"
+OCF_RESKEY_server_port_default="8977"
 
 : ${OCF_RESKEY_binary=${OCF_RESKEY_binary_default}}
 : ${OCF_RESKEY_config=${OCF_RESKEY_config_default}}
 : ${OCF_RESKEY_user=${OCF_RESKEY_user_default}}
 : ${OCF_RESKEY_pid=${OCF_RESKEY_pid_default}}
-: ${OCF_RESKEY_amqp_server_port=${OCF_RESKEY_amqp_server_port_default}}
+: ${OCF_RESKEY_server_port=${OCF_RESKEY_server_port_default}}
 
 #######################################################################
 
@@ -54,14 +50,14 @@ usage() {
     cat <<UEND
         usage: $0 (start|stop|validate-all|meta-data|status|monitor)
 
-        $0 manages an OpenStack Cinder Scheduler Service (cinder-schedule) process as an HA resource
+        $0 manages an OpenStack Panko API Service (panko-api) process as an HA resource
 
-        The 'start' operation starts the scheduler service.
-        The 'stop' operation stops the scheduler service.
+        The 'start' operation starts the panko-api service.
+        The 'stop' operation stops the panko-api service.
         The 'validate-all' operation reports whether the parameters are valid
         The 'meta-data' operation reports this RA's meta-data information
-        The 'status' operation reports whether the scheduler service is running
-        The 'monitor' operation reports whether the scheduler service seems to be working
+        The 'status' operation reports whether the panko-api service is running
+        The 'monitor' operation reports whether the panko-api service seems to be working
 
 UEND
 }
@@ -70,63 +66,63 @@ meta_data() {
     cat <<END
 <?xml version="1.0"?>
 <!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
-<resource-agent name="cinder-schedule">
+<resource-agent name="panko-api">
 <version>1.0</version>
 
 <longdesc lang="en">
-Resource agent for the OpenStack Cinder Scheduler Service (cinder-schedule)
-May manage a cinder-schedule instance or a clone set that
-creates a distributed cinder-schedule cluster.
+Resource agent for the OpenStack Panko API Service (panko-api)
+May manage a panko-api instance or a clone set that
+creates a distributed panko-api cluster.
 </longdesc>
-<shortdesc lang="en">Manages the OpenStack Cinder Scheduler Service (cinder-schedule)</shortdesc>
+<shortdesc lang="en">Manages the OpenStack Panko API Service (panko-api)</shortdesc>
 <parameters>
 
 <parameter name="binary" unique="0" required="0">
 <longdesc lang="en">
-Location of the OpenStack Cinder Scheduler server binary (cinder-schedule)
+Location of the OpenStack Panko API server binary (panko-api)
 </longdesc>
-<shortdesc lang="en">OpenStack Cinder Scheduler server binary (cinder-schedule)</shortdesc>
+<shortdesc lang="en">OpenStack Panko API server binary (panko-api)</shortdesc>
 <content type="string" default="${OCF_RESKEY_binary_default}" />
 </parameter>
 
 <parameter name="config" unique="0" required="0">
 <longdesc lang="en">
-Location of the OpenStack Cinder Scheduler Service (cinder-schedule) configuration file
+Location of the OpenStack Panko API Service (panko-api) configuration file
 </longdesc>
-<shortdesc lang="en">OpenStack Cinder Scheduler (cinder-schedule registry) config file</shortdesc>
+<shortdesc lang="en">OpenStack Panko API (panko-api) config file</shortdesc>
 <content type="string" default="${OCF_RESKEY_config_default}" />
 </parameter>
 
 <parameter name="user" unique="0" required="0">
 <longdesc lang="en">
-User running OpenStack Cinder Scheduler Service (cinder-schedule)
+User running OpenStack Panko API Service (panko-api)
 </longdesc>
-<shortdesc lang="en">OpenStack Cinder Scheduler Service (cinder-schedule) user</shortdesc>
+<shortdesc lang="en">OpenStack Panko API Service (panko-api) user</shortdesc>
 <content type="string" default="${OCF_RESKEY_user_default}" />
 </parameter>
 
 <parameter name="pid" unique="0" required="0">
 <longdesc lang="en">
-The pid file to use for this OpenStack Cinder Scheduler Service (cinder-schedule) instance
+The pid file to use for this OpenStack Panko API Service (panko-api) instance
 </longdesc>
-<shortdesc lang="en">OpenStack Cinder Scheduler Service (cinder-schedule) pid file</shortdesc>
+<shortdesc lang="en">OpenStack Panko API Service (panko-api) pid file</shortdesc>
 <content type="string" default="${OCF_RESKEY_pid_default}" />
 </parameter>
 
-<parameter name="amqp_server_port" unique="0" required="0">
+<parameter name="server_port" unique="0" required="0">
 <longdesc lang="en">
-The listening port number of the AMQP server. Use for monitoring purposes
-</longdesc>
-<shortdesc lang="en">AMQP listening port</shortdesc>
-<content type="integer" default="${OCF_RESKEY_amqp_server_port_default}" />
-</parameter>
+The listening port number of the panko-api server.
 
+</longdesc>
+<shortdesc lang="en">panko-api listening port</shortdesc>
+<content type="integer" default="${OCF_RESKEY_server_port_default}" />
+</parameter>
 
 <parameter name="additional_parameters" unique="0" required="0">
 <longdesc lang="en">
-Additional parameters to pass on to the OpenStack Cinder Scheduler Service (cinder-schedule)
+Additional parameters to pass on to the OpenStack Panko API Service (panko-api)
 </longdesc>
-<shortdesc lang="en">Additional parameters for cinder-schedule</shortdesc>
+<shortdesc lang="en">Additional parameters for panko-api</shortdesc>
 <content type="string" />
 </parameter>
 
@@ -147,7 +143,7 @@ END
 #######################################################################
 # Functions invoked by resource manager actions
 
-cinder_scheduler_check_port() {
+panko_api_check_port() {
 # This function has been taken from the squid RA and improved a bit
 # The length of the integer must be 4
 # Examples of valid port: "1080", "0080"
@@ -155,7 +151,7 @@ cinder_scheduler_check_port() {
 
     local int
     local cnt
-    
+
     int="$1"
     cnt=${#int}
     echo $int |egrep -qx '[0-9]+(:[0-9]+)?(,[0-9]+(:[0-9]+)?)*'
@@ -166,13 +162,13 @@ cinder_scheduler_check_port() {
     fi
 }
 
-cinder_scheduler_validate() {
+panko_api_validate() {
     local rc
 
     check_binary $OCF_RESKEY_binary
     check_binary netstat
-    cinder_scheduler_check_port $OCF_RESKEY_amqp_server_port
-    
+    panko_api_check_port $OCF_RESKEY_server_port
+
     # A config file on shared storage that is not available
     # during probes is OK.
     if [ ! -f $OCF_RESKEY_config ]; then
@@ -193,12 +189,12 @@ cinder_scheduler_validate() {
     true
 }
 
-cinder_scheduler_status() {
+panko_api_status() {
     local pid
     local rc
 
     if [ ! -f $OCF_RESKEY_pid ]; then
-        ocf_log info "OpenStack Cinder Scheduler (cinder-schedule) is not running"
+        ocf_log info "OpenStack Panko API (panko-api) is not running"
         return $OCF_NOT_RUNNING
     else
         pid=`cat $OCF_RESKEY_pid`
@@ -209,18 +205,19 @@ cinder_scheduler_status() {
     if [ $rc -eq 0 ]; then
         return $OCF_SUCCESS
     else
-        ocf_log info "Old PID file found, but OpenStack Cinder Scheduler (cinder-schedule) is not running"
+        ocf_log info "Old PID file found, but OpenStack Panko API (panko-api) is not running"
         rm -f $OCF_RESKEY_pid
         return $OCF_NOT_RUNNING
     fi
 }
 
-cinder_scheduler_monitor() {
+panko_api_monitor() {
     local rc
     local pid
-    local scheduler_amqp_check
+    local rc_db
+    local engine_db_check
 
-    cinder_scheduler_status
+    panko_api_status
     rc=$?
 
     # If status returned anything but success, return that immediately
@@ -228,52 +225,52 @@ cinder_scheduler_monitor() {
         return $rc
     fi
 
-    # Check the connections according to the PID.
-    # We are sure to hit the scheduler process and not other Cinder process with the same connection behavior (for example cinder-api)
-        pid=`cat $OCF_RESKEY_pid`
-        scheduler_amqp_check=`netstat -punt | grep -s "$OCF_RESKEY_amqp_server_port" | grep -s "$pid" | grep -qs "ESTABLISHED"`
-        rc=$?
-        if [ $rc -ne 0 ]; then
-        ocf_log err "Cinder Scheduler is not connected to the AMQP server : $rc"
-        return $OCF_NOT_RUNNING
-        fi
+    # Check the server is listening on the server port
+          engine_db_check=`netstat -an | grep -s "$OCF_RESKEY_console_port" | grep -qs "LISTEN"`
+          rc_db=$?
+          if [ $rc_db -ne 0 ]; then
+              ocf_log err "panko-api is not listening on $OCF_RESKEY_console_port: $rc_db"
+              return $OCF_NOT_RUNNING
+          fi
 
-    ocf_log debug "OpenStack Cinder Scheduler (cinder-schedule) monitor succeeded"
+    ocf_log debug "OpenStack Panko API (panko-api) monitor succeeded"
     return $OCF_SUCCESS
 }
 
-cinder_scheduler_start() {
+panko_api_start() {
     local rc
+    local host
 
-    cinder_scheduler_status
+    panko_api_status
     rc=$?
     if [ $rc -eq $OCF_SUCCESS ]; then
-        ocf_log info "OpenStack Cinder Scheduler (cinder-schedule) already running"
+        ocf_log info "OpenStack Panko API (panko-api) already running"
         return $OCF_SUCCESS
     fi
 
-    # run the actual cinder-schedule daemon. Don't use ocf_run as we're sending the tool's output
+    # run the actual panko-api daemon. Don't use ocf_run as we're sending the tool's output
     # straight to /dev/null anyway and using ocf_run would break stdout-redirection here.
-    su ${OCF_RESKEY_user} -s /bin/sh -c "${OCF_RESKEY_binary} --config-file=$OCF_RESKEY_config \
-       $OCF_RESKEY_additional_parameters"' >> /dev/null 2>&1 & echo $!' > $OCF_RESKEY_pid
+    su ${OCF_RESKEY_user}
+    /bin/python /usr/bin/gunicorn --config /usr/share/panko/panko-api.conf --access-logfile /dev/null \
+    --pythonpath /usr/share/panko panko-api >> /var/log/panko/panko-api.log 2>&1 & echo $! > $OCF_RESKEY_pid
 
     # Spin waiting for the server to come up.
     while true; do
-    cinder_scheduler_monitor
+    panko_api_monitor
     rc=$?
     [ $rc -eq $OCF_SUCCESS ] && break
     if [ $rc -ne $OCF_NOT_RUNNING ]; then
-        ocf_log err "OpenStack Cinder Scheduler (cinder-schedule) start failed"
+        ocf_log err "OpenStack Panko API (panko-api) start failed"
         exit $OCF_ERR_GENERIC
     fi
     sleep 1
     done
 
-    ocf_log info "OpenStack Cinder Scheduler (cinder-schedule) started"
+    ocf_log info "OpenStack Panko API (panko-api) started"
     return $OCF_SUCCESS
 }
 
-cinder_scheduler_confirm_stop() {
+panko_api_confirm_stop() {
     local my_bin
     local my_processes
 
@@ -287,15 +284,15 @@ cinder_scheduler_confirm_stop() {
     fi
 }
 
-cinder_scheduler_stop() {
+panko_api_stop() {
     local rc
     local pid
 
-    cinder_scheduler_status
+    panko_api_status
     rc=$?
     if [ $rc -eq $OCF_NOT_RUNNING ]; then
-        ocf_log info "OpenStack Cinder Scheduler (cinder-schedule) already stopped"
-        cinder_scheduler_confirm_stop
+        ocf_log info "OpenStack Panko API (panko-api) already stopped"
+        panko_api_confirm_stop
         return $OCF_SUCCESS
     fi
 
@@ -304,8 +301,8 @@ cinder_scheduler_stop() {
     ocf_run kill -s TERM $pid
     rc=$?
     if [ $rc -ne 0 ]; then
-        ocf_log err "OpenStack Cinder Scheduler (cinder-schedule) couldn't be stopped"
-        cinder_scheduler_confirm_stop
+        ocf_log err "OpenStack Panko API (panko-api) couldn't be stopped"
+        panko_api_confirm_stop
         exit $OCF_ERR_GENERIC
     fi
 
@@ -316,27 +313,27 @@ cinder_scheduler_stop() {
     fi
     count=0
     while [ $count -lt $shutdown_timeout ]; do
-        cinder_scheduler_status
+        panko_api_status
         rc=$?
         if [ $rc -eq $OCF_NOT_RUNNING ]; then
             break
         fi
         count=`expr $count + 1`
         sleep 1
-        ocf_log debug "OpenStack Cinder Scheduler (cinder-schedule) still hasn't stopped yet. Waiting ..."
+        ocf_log debug "OpenStack Panko API (panko-api) still hasn't stopped yet. Waiting ..."
     done
 
-    cinder_scheduler_status
+    panko_api_status
     rc=$?
     if [ $rc -ne $OCF_NOT_RUNNING ]; then
         # SIGTERM didn't help either, try SIGKILL
-        ocf_log info "OpenStack Cinder Scheduler (cinder-schedule) failed to stop after ${shutdown_timeout}s \
+        ocf_log info "OpenStack Panko API (panko-api) failed to stop after ${shutdown_timeout}s \
           using SIGTERM. Trying SIGKILL ..."
         ocf_run kill -s KILL $pid
     fi
-    cinder_scheduler_confirm_stop
+    panko_api_confirm_stop
 
-    ocf_log info "OpenStack Cinder Scheduler (cinder-schedule) stopped"
+    ocf_log info "OpenStack Panko API (panko-api) stopped"
 
     rm -f $OCF_RESKEY_pid
 
@@ -346,22 +343,23 @@ cinder_scheduler_stop() {
 #######################################################################
 
 case "$1" in
-  meta-data) meta_data
+  meta-data)    meta_data
                 exit $OCF_SUCCESS;;
-  usage|help) usage
+  usage|help)   usage
                 exit $OCF_SUCCESS;;
 esac
 
 # Anything except meta-data and help must pass validation
-cinder_scheduler_validate || exit $?
+panko_api_validate || exit $?
 
 # What kind of method was invoked?
 case "$1" in
-  start) cinder_scheduler_start;;
-  stop) cinder_scheduler_stop;;
-  status) cinder_scheduler_status;;
-  monitor) cinder_scheduler_monitor;;
+  start)        panko_api_start;;
+  stop)         panko_api_stop;;
+  status)       panko_api_status;;
+  monitor)      panko_api_monitor;;
   validate-all) ;;
-  *) usage
+  *)            usage
                 exit $OCF_ERR_UNIMPLEMENTED;;
 esac
+
